<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_My Account</name>
   <tag></tag>
   <elementGuidId>38deb21d-11ef-43e2-ae92-ef232fc5ccf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.my-account.icon__expand-arrow > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6713cf3-4f39-4ec5-b5cd-9630fd05ac81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Account</value>
      <webElementGuid>e788249c-5058-4f18-a1a4-04b7c758005a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html-body&quot;)/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;page-header-inner&quot;]/div[@class=&quot;header content&quot;]/div[@class=&quot;header content__right&quot;]/div[@class=&quot;my-account icon__expand-arrow&quot;]/span[1]</value>
      <webElementGuid>15170e7b-b135-4fd1-9f4e-301db1c82959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='html-body']/div[2]/header/div/div/div[3]/div/span</value>
      <webElementGuid>0691dc8a-8b6e-491c-b221-4ae9e8b74e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy &amp; Get Registration'])[2]/following::span[1]</value>
      <webElementGuid>f37608b9-a1bd-4f16-a415-0ea6d95a8c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warranty Registration'])[2]/following::span[1]</value>
      <webElementGuid>1e21cf16-1074-483a-9739-db6eb3e8b85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Shopping Cart'])[1]/preceding::span[6]</value>
      <webElementGuid>20581327-7976-418f-9f07-ed3b010a9140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account']/parent::*</value>
      <webElementGuid>62ad6982-3b75-4c19-9aaf-6b25b0d878a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>06b5f2e2-c6f3-461d-bc85-af345062d915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'My Account' or . = 'My Account')]</value>
      <webElementGuid>a56003e0-73c1-4b6b-9a1a-b5dcdc95fb19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
