<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rstico</name>
   <tag></tag>
   <elementGuidId>362e9352-b6ae-440c-9034-3f9eee6955b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='submenu-register-predio']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0d00664-2fca-4964-b077-1db77548d25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>cadastrar-patrimonio?patrimonyTypeV3=03&amp;operation=01</value>
      <webElementGuid>f506e727-6019-43df-bf16-2817fd86fe1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Rústico
                                    </value>
      <webElementGuid>2a7f3109-da90-4e5f-96fa-f3b82521880c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-register-predio&quot;)/li[2]/a[1]</value>
      <webElementGuid>7c82bce4-dfe6-4687-a8ff-24aaf63e1cc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='submenu-register-predio']/li[2]/a</value>
      <webElementGuid>0c1d6ba6-ad58-405e-a3e8-b88b00e3b7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propriedade Total'])[1]/following::a[1]</value>
      <webElementGuid>48075fb1-2553-42dc-adc6-f173ca99b67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horizontal'])[1]/following::a[2]</value>
      <webElementGuid>59138ded-1abd-45d1-b59e-1fd763bf5ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fracção'])[1]/preceding::a[1]</value>
      <webElementGuid>0c17e64d-6194-4e2b-9d5c-3da6a76b2939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'cadastrar-patrimonio?patrimonyTypeV3=03&amp;operation=01')]</value>
      <webElementGuid>31b36c22-d8a4-4f27-b4e3-d042b88841ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>3c874c02-eca5-4035-b937-d6a7cdf2445d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'cadastrar-patrimonio?patrimonyTypeV3=03&amp;operation=01' and (text() = '
                                        Rústico
                                    ' or . = '
                                        Rústico
                                    ')]</value>
      <webElementGuid>c108a70b-3cff-4870-8376-c6f8c559b981</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
