<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Design</name>
   <tag></tag>
   <elementGuidId>1d6fece7-86aa-4de7-af81-6890ec4ecbb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_T19FA31EB022_Col00']/details[4]/summary/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a26d5ab-309a-428e-8003-3190f794d7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/blogs/design</value>
      <webElementGuid>2bfe920b-21fa-4c14-a510-750cbdaa8132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Design</value>
      <webElementGuid>fec2d2e6-d941-417a-b200-87a816c2e59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_T19FA31EB022_Col00&quot;)/details[@class=&quot;BlogPost-Topics-Menu&quot;]/summary[1]/a[1]</value>
      <webElementGuid>55893294-016f-4004-93c2-163bd4f8b5b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_T19FA31EB022_Col00']/details[4]/summary/a</value>
      <webElementGuid>0a8d87ab-7149-4f95-b58a-1f809507591d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Design')]</value>
      <webElementGuid>a02a1a5b-3719-4f7c-bb18-b4dba6b4a857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blazor Desktop/.NET MAUI'])[4]/following::a[1]</value>
      <webElementGuid>65676141-db96-4b58-a680-d21ec45ff587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WPF'])[1]/following::a[2]</value>
      <webElementGuid>e32e2e62-2ae8-49f0-993c-aade72094ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UX'])[1]/preceding::a[1]</value>
      <webElementGuid>1b4f00e9-b80e-4358-a21d-84c841babb9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design Systems'])[1]/preceding::a[2]</value>
      <webElementGuid>ca2bd88d-ed84-475d-926a-16a71db2b566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Design']/parent::*</value>
      <webElementGuid>8bf9517f-a96b-4c30-9a27-887430b54eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/blogs/design')]</value>
      <webElementGuid>8b591b76-cbce-4325-90ba-2b223dcd4f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[4]/summary/a</value>
      <webElementGuid>2e4c2e93-253a-4be1-8cb2-0fad38b06548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/blogs/design' and (text() = 'Design' or . = 'Design')]</value>
      <webElementGuid>bed32b43-38d6-4c4a-93f1-044692a17ce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
