<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Get A Free Trial</name>
   <tag></tag>
   <elementGuidId>795d3006-bd82-4de3-9454-12face95eecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-tlrk-nav-drawer']/ul[2]/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.TK-Button.TK-Button--CTA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cdb74d64-2683-4958-91bf-e0eab15433a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/download</value>
      <webElementGuid>d8492b97-abd6-4262-8d4d-a56adc6041b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TK-Button TK-Button--CTA</value>
      <webElementGuid>a46a6cc4-3baf-4214-bc19-39d23fe26817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get A Free Trial</value>
      <webElementGuid>486a4ddf-0e81-4f83-bb29-f98f71cea474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-tlrk-nav-drawer&quot;)/ul[@class=&quot;TK-Aside-Menu TK-Aside-Menu--Max&quot;]/li[@class=&quot;TK-Aside-Menu-Item TK-bn&quot;]/a[@class=&quot;TK-Button TK-Button--CTA&quot;]</value>
      <webElementGuid>054741ef-6c68-4a27-81b3-e4a2334e367c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-tlrk-nav-drawer']/ul[2]/li[5]/a</value>
      <webElementGuid>67a765d0-1985-42d0-9d4b-665e66aebb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get A Free Trial')]</value>
      <webElementGuid>d75c010e-dbb5-47a0-a6e1-a876c4478984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::a[1]</value>
      <webElementGuid>695b5750-fab1-4831-b43c-72fa79227d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[2]</value>
      <webElementGuid>a8c255e0-e8e2-4216-bf76-140d39993118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close mobile menu'])[1]/preceding::a[1]</value>
      <webElementGuid>13a7ef22-6320-468d-a266-793641f71ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demos'])[2]/preceding::a[1]</value>
      <webElementGuid>6b8b3105-0de0-4bb8-ba56-c23b69dd684b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get A Free Trial']/parent::*</value>
      <webElementGuid>06375519-2cb6-49ee-93b9-8fbe9d43f0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/download')]</value>
      <webElementGuid>0209cab5-1f05-47c1-a383-b4af368f60e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[5]/a</value>
      <webElementGuid>24861ef3-be07-4808-bb8e-8206c636537c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/download' and (text() = 'Get A Free Trial' or . = 'Get A Free Trial')]</value>
      <webElementGuid>ea9188a0-5e07-4f0a-80c0-3b8d2a4d2f15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
