<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mobile</name>
   <tag></tag>
   <elementGuidId>b77c8a52-f558-4e0b-98f2-c177dc937764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_T19FA31EB022_Col00']/details[2]/summary/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64e42d96-194b-4858-8fdc-766a2e72f40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/blogs/mobile</value>
      <webElementGuid>5facf633-b192-4d2f-b875-9719aeff4855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile</value>
      <webElementGuid>f9fb1608-0c6f-413e-ac72-61271cb2f2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_T19FA31EB022_Col00&quot;)/details[@class=&quot;BlogPost-Topics-Menu&quot;]/summary[1]/a[1]</value>
      <webElementGuid>28998206-9615-4ecc-ab3d-c7d83e1c41a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_T19FA31EB022_Col00']/details[2]/summary/a</value>
      <webElementGuid>8b5a97c4-7727-42e3-8a45-5fbe31e87f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mobile')]</value>
      <webElementGuid>73c522d6-2b54-4733-a66d-a84b0e75ee8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vue'])[3]/following::a[1]</value>
      <webElementGuid>84583e58-373c-44d4-82d5-60e04ab21c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='React'])[3]/following::a[2]</value>
      <webElementGuid>2190c56b-bf52-4336-b999-78586134c6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xamarin'])[1]/preceding::a[1]</value>
      <webElementGuid>68404556-6a5b-4a70-a210-13bbdbf59426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.NET MAUI'])[1]/preceding::a[2]</value>
      <webElementGuid>769d368f-4328-4237-b80a-b0f7803c48e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/blogs/mobile')]</value>
      <webElementGuid>e4c0527e-7bc9-4685-baee-4b42a4885e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[2]/summary/a</value>
      <webElementGuid>5b74150b-cbd0-4f12-8246-5deda02e395e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/blogs/mobile' and (text() = 'Mobile' or . = 'Mobile')]</value>
      <webElementGuid>9420806b-7790-4af1-8039-9f264eb6c603</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
