<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_People</name>
   <tag></tag>
   <elementGuidId>39679c60-30a5-4a72-a4a1-3d6c762538d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_T19FA31EB022_Col00']/details[6]/summary/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ed8b029-a2b5-467d-900e-c4758ce87503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/blogs/people</value>
      <webElementGuid>7adb0983-6340-4514-9d1d-eb4e5b33311c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-instance</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>945d5711-bc1e-48bb-90f6-0203116cbd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>People</value>
      <webElementGuid>78de95ae-f9bd-4eb8-b00c-22b67beda0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_T19FA31EB022_Col00&quot;)/details[@class=&quot;BlogPost-Topics-Menu&quot;]/summary[1]/a[1]</value>
      <webElementGuid>2bbc7f1e-dd6d-45d2-9e01-7799e1c3926e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_T19FA31EB022_Col00']/details[6]/summary/a</value>
      <webElementGuid>5220cc66-322b-4987-85f4-63c81f4d1920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'People')])[2]</value>
      <webElementGuid>d1308982-7b9f-4055-8aca-ea7c067e130f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Processing'])[1]/following::a[1]</value>
      <webElementGuid>ac3ab478-4363-4cec-806b-74220f83c520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/following::a[2]</value>
      <webElementGuid>08c11c72-2bcb-4388-835d-2faade922953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[2]/preceding::a[1]</value>
      <webElementGuid>e84f64e3-1c2f-4ed5-8746-bea1ffff7878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Humanity'])[1]/preceding::a[2]</value>
      <webElementGuid>3e738a55-7e7c-49b4-8530-8fcd7301e5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/blogs/people')])[3]</value>
      <webElementGuid>0fe7847a-4901-4dcc-8d03-38fefbc2ac90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[6]/summary/a</value>
      <webElementGuid>4565cac9-10f3-4baa-8399-34b0c684d2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/blogs/people' and (text() = 'People' or . = 'People')]</value>
      <webElementGuid>0361478e-590b-4f5e-b23b-1037116b74fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
