<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Try now</name>
   <tag></tag>
   <elementGuidId>d7b33609-c5db-42fe-8e13-a1702cd96ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_C326_Col01']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.Btn.Btn--prim3.u-fs15.u-w10.u-p1.u-mt1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a98a3cd-02b7-40aa-8be4-059bf278b415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Btn Btn--prim3 u-fs15 u-w10 u-p1 u-mt1</value>
      <webElementGuid>1785c263-c624-4226-b559-fa5feaf69044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/try/devcraft-ultimate</value>
      <webElementGuid>8d3341a7-d414-4dae-be42-7547d4e90f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Try now</value>
      <webElementGuid>530bcbc1-57f6-4cdb-9ef5-7ddce1b68e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_C326_Col01&quot;)/a[@class=&quot;Btn Btn--prim3 u-fs15 u-w10 u-p1 u-mt1&quot;]</value>
      <webElementGuid>f24c8785-f17b-4eb4-9653-9951cdda8bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_C326_Col01']/a</value>
      <webElementGuid>7a68156e-b62d-4a58-a6c2-efd555a9d597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Try now')]</value>
      <webElementGuid>ce3d5fe5-ddca-486e-82ab-73cfb84c49b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telerik DevCraft'])[1]/following::a[1]</value>
      <webElementGuid>ebcc77db-e0b5-4873-ae30-983b57584513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Trials'])[1]/following::a[1]</value>
      <webElementGuid>03a5654f-ac7f-4a2a-9deb-eb8e5677a00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kendo UI'])[2]/preceding::a[1]</value>
      <webElementGuid>22c237e4-2baa-453f-910c-78182fd5255c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UI for Angular'])[2]/preceding::a[2]</value>
      <webElementGuid>7633db18-458f-46f9-bd0b-c09efc54d094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Try now']/parent::*</value>
      <webElementGuid>94122503-74ae-40c0-bb27-0aea46d8e0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/try/devcraft-ultimate')]</value>
      <webElementGuid>c0b7a737-fd1a-4b4e-9798-20b5a00adfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div[2]/a</value>
      <webElementGuid>f8e97d7d-4350-4404-90c6-8ab988b721bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/try/devcraft-ultimate' and (text() = 'Try now' or . = 'Try now')]</value>
      <webElementGuid>d84de0c7-e25c-4928-b6db-98699bc223a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
