<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get A Free Trial_js-tlrk-nav-drawer-button</name>
   <tag></tag>
   <elementGuidId>42c6d4a7-6e33-4910-b6cb-b2c6dfa8aa06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-tlrk-nav-drawer-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js-tlrk-nav-drawer-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b585fb5-f990-4f01-817e-e022740d9649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c35ee466-97c6-4508-9b9d-a4989db3d2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>cf0b823f-863a-4805-953c-5c56e78f783a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TK-Aside-Menu-Button TK-Aside-Menu-Button--Toggle-Drawer</value>
      <webElementGuid>c8ac3c41-8ba8-4d54-901d-bdf281bd987a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-tlrk-nav-drawer-button</value>
      <webElementGuid>48620d27-68b5-4f36-8360-807ab97c2713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-tlrk-nav-drawer-button&quot;)</value>
      <webElementGuid>89389c6a-bd51-4e55-82e8-5ca938033540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js-tlrk-nav-drawer-button']</value>
      <webElementGuid>32052b83-b5d0-41ae-a389-900f999b759c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='js-tlrk-nav']/section/div/div[3]/ul/li/button</value>
      <webElementGuid>4def4ebb-72d5-4119-b646-9654650c3193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get A Free Trial'])[1]/following::button[1]</value>
      <webElementGuid>4448be68-fc1e-40cd-a5ad-5d9bb501d5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::button[1]</value>
      <webElementGuid>ee501fd5-1acc-44c1-8ce4-344a24643152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close mobile menu'])[1]/preceding::button[1]</value>
      <webElementGuid>df53c24e-91ca-4cef-b018-f020564ed68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demos'])[2]/preceding::button[2]</value>
      <webElementGuid>7efcb77b-6178-4c92-a903-b8440ce7f797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/button</value>
      <webElementGuid>0408843d-9089-4b36-b547-a0a95814ea7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'js-tlrk-nav-drawer-button']</value>
      <webElementGuid>a5c56c18-4bee-47a0-a72a-a6abbe303601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
