<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Microsoft Brand Page_lazyload</name>
   <tag></tag>
   <elementGuidId>d84c814b-0701-491e-aa55-a904e1b83821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>539c6458-6d62-494c-89d7-61cd00f70346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyload</value>
      <webElementGuid>72682b1b-45c6-45a1-ba4b-37a384a8051b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.incredible.co.za/media/wysiwyg/IC_microsoft_brand_page/2_Windows_11.png</value>
      <webElementGuid>9fb843d2-e665-45e2-96f4-c329c90e58d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>29f52b04-6efa-426b-b0fb-7e05d42aeb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.incredible.co.za/media/wysiwyg/IC_microsoft_brand_page/2_Windows_11.png</value>
      <webElementGuid>56670ceb-b867-4612-befe-f7468ca7a4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;category-view&quot;]/div[@class=&quot;category-cms&quot;]/div[@class=&quot;cms-services-slider&quot;]/div[@class=&quot;row-full-width-inner&quot;]/div[1]/div[@class=&quot;brands-icbrandtestnew zoom-effect-container slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/a[@class=&quot;zoom-effect&quot;]/img[@class=&quot;lazyload&quot;]</value>
      <webElementGuid>2538439d-fefb-4873-9e14-b150690058d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>952cdf67-271b-4f0f-b634-c228ad02d7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.incredible.co.za/media/wysiwyg/IC_microsoft_brand_page/2_Windows_11.png')]</value>
      <webElementGuid>f2bb85a4-30a3-45ec-82f4-11866a8cb349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>f18f00e0-85ab-4bfe-bf74-b8dc4db36a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.incredible.co.za/media/wysiwyg/IC_microsoft_brand_page/2_Windows_11.png']</value>
      <webElementGuid>6a2bf90e-4415-4663-9947-728e69c4edd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
