<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Atualidade</name>
   <tag></tag>
   <elementGuidId>21c4cf30-5159-4bd0-bd27-dfd32a1644eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3509']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7725c54-c6b1-4725-817b-f0a6ee7f55c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://koffieluso.com/atualidade/</value>
      <webElementGuid>d275aa65-f9cf-46d5-b1fe-c0e7a23799f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>49f7c9c3-4466-4803-aba5-c507f1316e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atualidade</value>
      <webElementGuid>a59d979a-4802-4c45-9b32-cf85fd614983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3509&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>00635468-4c7f-43ed-adf1-346d43c27713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3509']/a</value>
      <webElementGuid>1cfb3a82-b50b-4e1f-a0b7-f611fa1b3d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Atualidade')]</value>
      <webElementGuid>7ee55061-4135-4f0e-9349-3c7b0530ca8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='“Piano” de Stefânia Leonel e Dj Tarico'])[1]/following::a[3]</value>
      <webElementGuid>e57efa96-0152-424e-86ac-71e333321d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cultura &amp; Arte'])[1]/preceding::a[1]</value>
      <webElementGuid>4ea7e693-fdd2-45fc-a7a2-402ed229195e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Música'])[1]/preceding::a[2]</value>
      <webElementGuid>f5ac9cc0-2504-445a-9005-63125ed398f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Atualidade']/parent::*</value>
      <webElementGuid>6b53caa8-894c-4e25-af71-f94799d04a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://koffieluso.com/atualidade/')]</value>
      <webElementGuid>45ea5d90-c02b-462e-9fdb-a1b2e31efff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>472cda44-f8b4-4c59-b9a4-7c0bdade254c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://koffieluso.com/atualidade/' and (text() = 'Atualidade' or . = 'Atualidade')]</value>
      <webElementGuid>146b2853-04ce-4a9f-8d3d-d760f82b91f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
