<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rstico</name>
   <tag></tag>
   <elementGuidId>cde8da4f-2179-4626-8c62-f974b63cdd6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='submenu-register-predio']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d40a44e-7316-40bf-97e0-49d9f682b9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>cadastrar-patrimonio?patrimonyTypeV3=03&amp;operation=01</value>
      <webElementGuid>a5457324-a3bc-4a72-8f1b-63a46cb5fa0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Rústico
                                    </value>
      <webElementGuid>1b9645b0-72ca-450f-83d0-1bede1f75ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-register-predio&quot;)/li[2]/a[1]</value>
      <webElementGuid>5781a7e9-0191-4c6e-9b00-1e6b19b8d0e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='submenu-register-predio']/li[2]/a</value>
      <webElementGuid>24b36a7a-aa70-4304-bca4-b483e34999df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propriedade Total'])[1]/following::a[1]</value>
      <webElementGuid>f3f44c6f-e333-4753-8530-57ed70da51a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horizontal'])[1]/following::a[2]</value>
      <webElementGuid>4c135b81-cb89-4f75-9208-f92a6a24ac39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fracção'])[1]/preceding::a[1]</value>
      <webElementGuid>beabd2ff-2949-4e2c-9755-a1caab08defe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'cadastrar-patrimonio?patrimonyTypeV3=03&amp;operation=01')]</value>
      <webElementGuid>cccb13a8-d2cb-478c-bc9f-d1ea797b0781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>8048f1ee-92fe-4462-8e9a-1d18a7658137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'cadastrar-patrimonio?patrimonyTypeV3=03&amp;operation=01' and (text() = '
                                        Rústico
                                    ' or . = '
                                        Rústico
                                    ')]</value>
      <webElementGuid>226b519a-e70a-46f2-8640-34b599c64dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
