<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Seleccione</name>
   <tag></tag>
   <elementGuidId>2c09ed84-3af7-40f8-9a0c-a6c6328ad89e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5e1f07ac-94b9-4892-87a6-ea72a7bc96d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_label</value>
      <webElementGuid>cda37ff7-3b91-483c-b53f-8df15d239f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>e520b5df-f3ce-454a-8f90-91f8e8478fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione...</value>
      <webElementGuid>8a14fca7-d5af-4b00-91dc-fca8fb27f6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_label&quot;)</value>
      <webElementGuid>77715093-fac7-48c0-ab2d-3ba8dbccda26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_label']</value>
      <webElementGuid>73774179-4960-4054-a88e-b56cb81a7f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct']/label</value>
      <webElementGuid>769adc29-12cb-4c1d-a699-c520bcfbfffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Província*'])[1]/following::label[1]</value>
      <webElementGuid>9d78045b-251c-4b83-a004-99a7b68e200b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOCALIZAÇÃO'])[1]/following::label[2]</value>
      <webElementGuid>a8a2a24e-9c84-4259-87e4-005cf3df7213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município*'])[1]/preceding::label[1]</value>
      <webElementGuid>8417edb8-ef7f-4884-b668-b033368ce3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione...'])[8]/preceding::label[2]</value>
      <webElementGuid>a065597c-c234-4596-9f69-0d6bb86109f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/label</value>
      <webElementGuid>f0581b9b-967d-4588-a29d-efd0089e5249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_label' and (text() = 'Seleccione...' or . = 'Seleccione...')]</value>
      <webElementGuid>8e2e59f8-8fee-4ae7-8f1a-42985bb892dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
