<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Seleccione_1_2</name>
   <tag></tag>
   <elementGuidId>60cf3574-c8c2-4f3e-8242-0b82f1b4252b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>33518900-ef8d-43d4-b7cd-c37dcdf291ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_label</value>
      <webElementGuid>e80a708a-eeaa-4eee-955e-d289bf6cef97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>8ca0d390-2507-4e2e-a633-9ecf6bb83d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione...</value>
      <webElementGuid>5ae6ca01-3cf7-4404-813c-a5c7c1fbb885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_label&quot;)</value>
      <webElementGuid>0108ec98-46e3-403f-a3d2-8923c831b07c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_label']</value>
      <webElementGuid>b240f701-bc8f-43cd-9e2b-f58d0ca8b11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect']/label</value>
      <webElementGuid>bc0500e9-9e4f-4afd-9481-d3c33e22bc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distrito/Comuna*'])[1]/following::label[1]</value>
      <webElementGuid>66463762-ef52-497f-85ae-424347202301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LUANDA'])[4]/following::label[2]</value>
      <webElementGuid>7f5a5638-ae5c-407e-a0fe-c127849de87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bairro*'])[1]/preceding::label[1]</value>
      <webElementGuid>4b9b93aa-241f-4128-a4ee-2600ff0cefa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rua/Avenida*'])[1]/preceding::label[2]</value>
      <webElementGuid>7011eee7-0adb-44b4-a1a6-ffba52c6246f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label</value>
      <webElementGuid>050175b5-4463-4620-9b02-18d60097e32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_label' and (text() = 'Seleccione...' or . = 'Seleccione...')]</value>
      <webElementGuid>7f9bf95e-3264-4f4d-bf0d-e1ec3127e01b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
