<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Seleccione_1</name>
   <tag></tag>
   <elementGuidId>3be2c63a-9cf6-4dfe-a7e7-3b5e60497754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>dedc185d-aea1-4bb3-975d-c75b3c42f02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_label</value>
      <webElementGuid>25743312-eb45-43c9-ba4e-95b4673bbc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>a63e4f48-fb3e-4eb3-9918-73077cd6a9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione...</value>
      <webElementGuid>a3c118d8-5a07-42d4-b491-2f5eba916af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_label&quot;)</value>
      <webElementGuid>6effe7e3-c225-4f98-92c3-a21ba0143cc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_label']</value>
      <webElementGuid>42ab610b-b923-4d86-9154-0911e3aeea5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect']/label</value>
      <webElementGuid>d821720d-c1ba-41ec-90ac-aea01ab048e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município*'])[1]/following::label[1]</value>
      <webElementGuid>043eabdd-e113-4488-a370-86fa4d046a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LUANDA'])[2]/following::label[2]</value>
      <webElementGuid>931348fb-0fda-47ad-90f0-6d725920ffe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distrito/Comuna*'])[1]/preceding::label[1]</value>
      <webElementGuid>8baac594-3afd-4d0f-8a85-767b5e7e64db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione...'])[9]/preceding::label[2]</value>
      <webElementGuid>818da24e-3c2f-4114-a2d4-30e69a7024b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/label</value>
      <webElementGuid>2d321b5c-ac22-491a-bff4-8e3a2997e357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_label' and (text() = 'Seleccione...' or . = 'Seleccione...')]</value>
      <webElementGuid>ea55e6e9-c9aa-4acb-b459-59c1731ed6a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
