<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_LUANDA</name>
   <tag></tag>
   <elementGuidId>6ee6d6f1-9a61-4436-82e9-a55a4aab7231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>60065401-d30f-4446-9a5a-3e8eaa906f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>268d15c2-d0af-40cd-a4a1-fe84686edd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>LUANDA</value>
      <webElementGuid>3ed67e2f-aea4-463e-bbe8-14eb100296a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aaa79ea7-fb35-443f-915d-15b33fe1f7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ce8166f7-24a1-445f-8367-369a347ff97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_1</value>
      <webElementGuid>07b12eab-ab80-4d9a-aafe-19e819c7eb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LUANDA</value>
      <webElementGuid>d37fa21f-69ba-4cb4-8088-bb217af5054f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_1&quot;)</value>
      <webElementGuid>05a8f1a2-4049-4658-a515-0e42a047fa2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_1']</value>
      <webElementGuid>861a89d5-8ed2-4977-bd19-d602a0e78a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_items']/li[2]</value>
      <webElementGuid>b12e32dc-249a-4466-95bc-8e4821530281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione...'])[19]/following::li[1]</value>
      <webElementGuid>2adc3a9c-713a-4d34-9247-eb5c8e4e4b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outro'])[2]/following::li[2]</value>
      <webElementGuid>416e11ad-22f3-43a3-a17a-b9b26bd67690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione...'])[20]/preceding::li[1]</value>
      <webElementGuid>7579fc29-11c4-4599-9562-c5061c5af568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione...'])[21]/preceding::li[2]</value>
      <webElementGuid>9f9c8a55-29c2-4510-a68d-2b3a93991312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/ul/li[2]</value>
      <webElementGuid>07f4186a-0c20-4624-948c-94869be5393a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct_1' and (text() = 'LUANDA' or . = 'LUANDA')]</value>
      <webElementGuid>97c33357-41dc-4374-a92c-c48cb2dce5c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
