<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_LUANDA_1</name>
   <tag></tag>
   <elementGuidId>2d8b6c7d-ad29-46af-bced-13ed69a553c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>852845d1-1b7d-421b-ad03-f54c6112fc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>a4dfb86b-1ad7-4ac2-ad27-ec8bb35dea40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>LUANDA</value>
      <webElementGuid>a9724823-8a29-4c30-8e88-d274a18f1194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cceefb4c-7c15-4d6b-81db-39e96836e26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>28062ef2-1627-4cc2-b0b9-2c87dccf3819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_2</value>
      <webElementGuid>ddf5bb12-be2a-4538-b162-4025ccc94f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LUANDA</value>
      <webElementGuid>0f100ff8-7a9c-47cf-b4b0-deb1cc82c727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_2&quot;)</value>
      <webElementGuid>ba826795-9091-47cb-ae9a-e9e196aa87c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_2']</value>
      <webElementGuid>fce1fc35-7bdc-4b98-b436-4c489db9eea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_items']/li[3]</value>
      <webElementGuid>3b556b0b-c636-4adf-bca0-320c38956f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAZENGA'])[2]/following::li[1]</value>
      <webElementGuid>d54119ca-d08c-476f-8b7f-26f9246bb87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione...'])[19]/following::li[2]</value>
      <webElementGuid>159ea573-744d-4882-8092-d917c270a848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione...'])[20]/preceding::li[1]</value>
      <webElementGuid>6c353390-9f55-4001-9803-f201951458e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/ul/li[3]</value>
      <webElementGuid>3c1609e5-e3bf-4a31-84c8-3d13ea17c5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect_2' and (text() = 'LUANDA' or . = 'LUANDA')]</value>
      <webElementGuid>0778a80a-6a2c-4f4a-8c6a-b33482fbdda4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
