<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_RANGEL</name>
   <tag></tag>
   <elementGuidId>743d8a25-91f9-4d19-951c-fc48df079a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a01ceb8b-d37f-424b-8922-d295878f5372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>95fa0cba-23af-4892-a47d-f7a38c21a1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>RANGEL</value>
      <webElementGuid>0a032ed4-4699-48bf-916e-3c43e9725f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9516cf8e-ee67-4603-abe0-0c8704966281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c6b2c554-f373-4d22-98dc-2469a152324c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_2</value>
      <webElementGuid>69d9ca14-69bc-46f7-abdd-8a7662d6f6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RANGEL</value>
      <webElementGuid>42938772-780b-4b5e-b9dd-aeeb1d64898a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_2&quot;)</value>
      <webElementGuid>44840956-ded2-4414-a00f-7940365d1aa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_2']</value>
      <webElementGuid>025c72c1-1361-417e-b7ed-6ca23b4b59e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_items']/li[3]</value>
      <webElementGuid>f83c8bc0-a7b1-4844-a0f0-9946abefba70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NGOLA KILUANJE'])[2]/following::li[1]</value>
      <webElementGuid>898fc81a-d52f-4d61-8a73-44725d285304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione...'])[19]/following::li[2]</value>
      <webElementGuid>532d6f94-7e56-4e2a-9c56-6739db299f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAMBIZANGA'])[2]/preceding::li[1]</value>
      <webElementGuid>a8b81ded-b06f-451c-a7ad-1fddf89470dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/ul/li[3]</value>
      <webElementGuid>a2d902a5-280e-48df-8f76-3c2089ef6110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect_2' and (text() = 'RANGEL' or . = 'RANGEL')]</value>
      <webElementGuid>38ce3630-5388-498b-b395-377082809534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
