<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue with email</name>
   <tag></tag>
   <elementGuidId>bc5c12ce-f8e9-4d67-af68-fa799a5bbd90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._jwti9r > button._snbhip0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[155]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dde3043d-ae6a-4e1d-9989-6e43566ecbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>social-auth-button-email</value>
      <webElementGuid>ab7029e6-19cb-43c6-b585-615abb7e4048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Continue with email</value>
      <webElementGuid>28cbed74-ddfa-491d-b37a-0ce7500d281d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>669fc722-f2cd-4e55-bbd6-795595df6116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_snbhip0</value>
      <webElementGuid>be4e4dc3-21b3-496a-9af8-b0bc323ba18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with email</value>
      <webElementGuid>7bd66338-284f-431d-b77c-425f5f495866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scrollbar-gutter js-focus-visible&quot;]/body[@class=&quot;with-new-header&quot;]/div[13]/section[1]/div[@class=&quot;_vxvq8x&quot;]/div[@class=&quot;_z4lmgp&quot;]/div[@class=&quot;_z4lmgp&quot;]/div[@class=&quot;_1b64dznw&quot;]/div[@class=&quot;_12kfhdn&quot;]/div[1]/div[@class=&quot;_88xxct&quot;]/div[@class=&quot;_88sa87&quot;]/div[@class=&quot;_jwti9r&quot;]/button[@class=&quot;_snbhip0&quot;]</value>
      <webElementGuid>fd3866ad-035b-4949-9de4-e01171355046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[155]</value>
      <webElementGuid>3e8f41c3-7cae-43bf-a833-c5b54e037e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue with Apple'])[1]/following::button[1]</value>
      <webElementGuid>48dbc78e-2e48-495b-ba3a-4694bb262e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue with Google'])[1]/following::button[2]</value>
      <webElementGuid>b8ade884-0ccc-4f43-9e11-47fadab4e6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/button</value>
      <webElementGuid>b1e541c9-4e3d-43d8-863a-3e74902196d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Continue with email' or . = 'Continue with email')]</value>
      <webElementGuid>0739d2c8-743d-4b90-8502-b6bce4f3388a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
