<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(Check the box to verify that _39fc97</name>
   <tag></tag>
   <elementGuidId>9497716a-8fd5-4ab9-8491-2f74ce0884e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-y7ui876kcsr5&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-y7ui876kcsr5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>95016f0a-d7ee-45ad-8349-75f8b106f6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>f20ee433-ad56-4d9c-891a-5aa86543f4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&amp;k=6Lf20R0UAAAAAJDj8fQYXmFJWTbSPtvhtjV0VFoy&amp;co=aHR0cHM6Ly93d3cuYWlyYm5iLmNvbTo0NDM.&amp;hl=en&amp;v=gEr-ODersURoIfof1hiDm7R5&amp;size=normal&amp;cb=4gaiu19form</value>
      <webElementGuid>d6e134ed-ea62-4228-818d-be46968c055e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>dd1ac9f2-700f-4f18-a48a-6b6eeba57215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>05dc99f5-cdfb-4386-8506-4271ccba79c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>8e985520-92d7-4cbe-9aca-bbd19c8176b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-y7ui876kcsr5</value>
      <webElementGuid>8543c5df-db15-4910-94a7-4ee960f99a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1c57651d-7f30-420a-aaed-ae9baf2fa89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6f065390-3465-4c02-967e-7bd6b76b46c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>86308d2f-60ab-4318-b7d3-9131a2b10b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>cb6854ca-1f38-47eb-becd-937691b6f52f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-y7ui876kcsr5']</value>
      <webElementGuid>538eb90b-ec1a-4396-a967-393367fc113f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha']/div/div/iframe</value>
      <webElementGuid>4f5afb68-1b8f-465f-8aa4-bb3bc7055791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/iframe</value>
      <webElementGuid>93a037b8-3dde-44be-8cec-5d27bf5f5d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&amp;k=6Lf20R0UAAAAAJDj8fQYXmFJWTbSPtvhtjV0VFoy&amp;co=aHR0cHM6Ly93d3cuYWlyYm5iLmNvbTo0NDM.&amp;hl=en&amp;v=gEr-ODersURoIfof1hiDm7R5&amp;size=normal&amp;cb=4gaiu19form' and @name = 'a-y7ui876kcsr5']</value>
      <webElementGuid>18c86910-4aeb-4931-8e46-8cee72c70bf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
