<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_phoneInputphoneNumber</name>
   <tag></tag>
   <elementGuidId>e697d6ae-1c69-4b55-9aca-5b24753dc9e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phoneInputphoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneInputphoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6827ab74-b2cc-42e0-a24d-caaf56e1c2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneInputphoneNumber</value>
      <webElementGuid>2242868f-fdbb-4dda-a013-972073d1b3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61585e2b-c936-4956-9a5e-2eddc4bd07ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>login-signup-phonenumber</value>
      <webElementGuid>5afe7829-8bd3-4018-a8d2-d8bb9e930f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1udbwkg focus-visible</value>
      <webElementGuid>b1ca0671-7531-4853-a63f-d25fdb717316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneInputphoneNumber</value>
      <webElementGuid>eb6cd1ec-1f04-41fc-b80f-fcbebcf15d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel-national</value>
      <webElementGuid>0063886c-69cb-45fc-aea7-365359019cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3098fbb1-9d2a-424c-88e3-70fcf19b80d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>5f0ad02c-0f79-4e22-a4cd-faa568cdf57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>phone-number-help-text-phoneNumber airlock-inline-container</value>
      <webElementGuid>6cdc6a52-7437-4e3b-9645-7f3986f36043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneInputphoneNumber&quot;)</value>
      <webElementGuid>21d87433-6d1d-453c-a004-0e217603efbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneInputphoneNumber']</value>
      <webElementGuid>7ea93a23-088c-4667-9ae4-8107547f2361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e3a14cf0-c6b9-4183-9777-e1052dc06d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phoneInputphoneNumber' and @id = 'phoneInputphoneNumber' and @type = 'tel']</value>
      <webElementGuid>301769e7-8526-4d73-ad02-00f7893bb973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
