<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Search resultsOver 1,000 homes in Atlanta</name>
   <tag></tag>
   <elementGuidId>de935cb7-b219-4f24-8297-2a4a76f0eb6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1._14i3z6h</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='site-content']/div[2]/div/div/div/div/div/section/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b700358a-d876-48a6-ac6e-1994d25e7edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bbe6cfa2-a196-43d5-b9ba-c79d9b79ece8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_14i3z6h</value>
      <webElementGuid>1b3c7f32-1d9b-442d-84de-ebdb6823dc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementtiming</name>
      <type>Main</type>
      <value>LCP-target</value>
      <webElementGuid>481291c9-2eb2-4e4f-8793-092d6e24492e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search resultsOver 1,000 homes in Atlanta</value>
      <webElementGuid>d7df4a5e-d92d-4392-a2fa-b4590b38c420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;fmdphkf dir dir-ltr&quot;]/div[@class=&quot;p1180s14 dir dir-ltr&quot;]/div[@class=&quot;c1yo0219 dir dir-ltr&quot;]/div[1]/div[@class=&quot;c1aasoj4 dir dir-ltr&quot;]/div[@class=&quot;t16kra9o dir dir-ltr&quot;]/section[1]/h1[@class=&quot;_14i3z6h&quot;]</value>
      <webElementGuid>6a9af468-5fcd-4d44-950c-fc53408573c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='site-content']/div[2]/div/div/div/div/div/section/h1</value>
      <webElementGuid>d9255f1f-e953-42ed-a9a4-b6ff8066f7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show map'])[1]/following::h1[1]</value>
      <webElementGuid>7f8d726c-c9f5-4301-a26c-39d63b67f857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::h1[1]</value>
      <webElementGuid>798602ef-4bfb-4d15-b9d6-e935c4000cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>301f5b0d-c55f-40b8-892d-a02fe8ac9041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Search resultsOver 1,000 homes in Atlanta' or . = 'Search resultsOver 1,000 homes in Atlanta')]</value>
      <webElementGuid>da86c433-aeba-4c74-b0e9-0a35b07a18e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
