<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy now</name>
   <tag></tag>
   <elementGuidId>8aaa13d5-8f68-4520-9174-dc09782e24dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Btn.Btn--prim4.u-db</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_C691_Col00']/div/div/div/table/thead/tr[5]/th/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>579bdfc7-a238-4994-a042-4302ab495b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://store.progress.com/configure-purchase?skuId=801&amp;_ga=2.112622212.1278319895.1675177359-747469.1675177359&amp;_gl=1*eyepto*_ga*NzQ3NDY5LjE2NzUxNzczNTk.*_ga_9JSNBCSF54*MTY3NTE3NzM1OS4xLjEuMTY3NTE3NzM2Ni41My4wLjA.</value>
      <webElementGuid>f7828230-6852-471b-80a5-788103e96e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Btn Btn--prim4 u-db</value>
      <webElementGuid>19182554-fa99-403f-9521-89c0e2cf557f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-instance</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3f43fecb-463c-4b74-a1dd-dd88334f89df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy now</value>
      <webElementGuid>1dc8b2b7-c506-4c86-bcc6-089df111f2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_C691_Col00&quot;)/div[@class=&quot;u-pr&quot;]/div[@class=&quot;Wrap is-collapsed&quot;]/div[@class=&quot;PricingTable-Wrap&quot;]/table[@class=&quot;PricingTable PricingTable--l u-fs18 k-table sticky-table&quot;]/thead[@class=&quot;track--pricing-head&quot;]/tr[@class=&quot;Pricings-button&quot;]/th[@class=&quot;UI is-active&quot;]/div[1]/a[@class=&quot;Btn Btn--prim4 u-db&quot;]</value>
      <webElementGuid>caee01d6-b9af-41ca-9409-cd52641acdf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_C691_Col00']/div/div/div/table/thead/tr[5]/th/div/a</value>
      <webElementGuid>62df03e0-3e9e-4fb4-afc7-cf744e77df1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buy now')]</value>
      <webElementGuid>504b3fd9-0efe-4b08-9977-279076892818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[9]/following::a[1]</value>
      <webElementGuid>f53c13ff-9928-49b2-924b-64fb2c9b2d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[8]/following::a[1]</value>
      <webElementGuid>de344052-cc20-4944-ba1a-fd8b3ad8d4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy now'])[2]/preceding::a[1]</value>
      <webElementGuid>e6ad7487-30d2-46d1-af7b-a94b9540ded5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy now'])[3]/preceding::a[2]</value>
      <webElementGuid>754d0248-2be6-4ce6-b977-bf60ca5c11d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy now']/parent::*</value>
      <webElementGuid>7720bab9-7093-4f9c-b947-9750f5c2af10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://store.progress.com/configure-purchase?skuId=801&amp;_ga=2.112622212.1278319895.1675177359-747469.1675177359&amp;_gl=1*eyepto*_ga*NzQ3NDY5LjE2NzUxNzczNTk.*_ga_9JSNBCSF54*MTY3NTE3NzM1OS4xLjEuMTY3NTE3NzM2Ni41My4wLjA.')]</value>
      <webElementGuid>c247cc3a-b3b8-4e82-90aa-5be56317bce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div/a</value>
      <webElementGuid>6e968184-fc08-465e-a6b0-95f2bcaf3c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://store.progress.com/configure-purchase?skuId=801&amp;_ga=2.112622212.1278319895.1675177359-747469.1675177359&amp;_gl=1*eyepto*_ga*NzQ3NDY5LjE2NzUxNzczNTk.*_ga_9JSNBCSF54*MTY3NTE3NzM1OS4xLjEuMTY3NTE3NzM2Ni41My4wLjA.' and (text() = 'Buy now' or . = 'Buy now')]</value>
      <webElementGuid>25fc785c-2b65-4b6e-aa0b-7987bb95408c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
