<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get A Free Trial_js-tlrk-nav-drawer-button</name>
   <tag></tag>
   <elementGuidId>f1b7e155-0b21-41bf-80bb-0409d72a198b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-tlrk-nav-drawer-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js-tlrk-nav-drawer-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76d59645-eb15-4188-ab1f-eb720c0a41b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a9c8aa8-4f02-497e-90dc-42fbaa96e043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>3b9a73b8-fa54-432d-a352-e1d05285b2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TK-Aside-Menu-Button TK-Aside-Menu-Button--Toggle-Drawer</value>
      <webElementGuid>413d2d1c-ae34-4388-914f-fb782f5c4e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-tlrk-nav-drawer-button</value>
      <webElementGuid>561a3006-12b9-493d-8015-b4f2c95f4853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-tlrk-nav-drawer-button&quot;)</value>
      <webElementGuid>703f56c0-49b6-44be-b7a4-65238110e5e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js-tlrk-nav-drawer-button']</value>
      <webElementGuid>6a528ffb-ac0e-4803-9f7c-2b3831119295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='js-tlrk-nav']/section/div/div[3]/ul/li/button</value>
      <webElementGuid>4ae90982-658d-491f-bca1-2dbfd93aff16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get A Free Trial'])[1]/following::button[1]</value>
      <webElementGuid>d8465cbf-ad19-4f41-8f6f-47df54db777d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::button[1]</value>
      <webElementGuid>70dc7fe2-6e08-4778-b16a-20066925f600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close mobile menu'])[1]/preceding::button[1]</value>
      <webElementGuid>fd12c85f-4639-4fa4-9cfd-6886ae9dcb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demos'])[2]/preceding::button[2]</value>
      <webElementGuid>3624e95c-0042-43f4-8895-d5814d1264bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/button</value>
      <webElementGuid>15f597c1-263b-4fab-b60a-6f4d62c5abc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'js-tlrk-nav-drawer-button']</value>
      <webElementGuid>f13175a2-7440-4bc8-b6f1-10dc6a5c880e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
