<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>fbb96b4b-0ee5-4c54-8825-77674d5f5cfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-accent.btn-lg.u-fr.e2e-continue.loader-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae835f43-7f0c-4c2a-b715-0102bc2030a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loadertype</name>
      <type>Main</type>
      <value>inline</value>
      <webElementGuid>9885512f-a425-483e-aff7-253f43535ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6e75b11-3b3c-4736-855c-3288bfbb0544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>trackevent</name>
      <type>Main</type>
      <value>store.progress.com, continue-btn, https://store.progress.com/contact-info</value>
      <webElementGuid>3da1b7c3-ec01-4641-b0bb-8e2b8c08e93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-accent btn-lg u-fr e2e-continue loader-container</value>
      <webElementGuid>9867d10f-9546-4a02-aafb-aae44aec7a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Continue
      </value>
      <webElementGuid>2856db69-d9d5-4440-a2af-52185e99f6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-body ng-tns-0-2&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;wrapper&quot;]/shopping-cart-app[1]/section[@class=&quot;container&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;panel contact-info-panel-wrapper panel-main ng-star-inserted&quot;]/div[@class=&quot;panel-body ng-star-inserted&quot;]/div[@class=&quot;row fx-fluid-container-sm fx-spacing-5&quot;]/button[@class=&quot;btn btn-accent btn-lg u-fr e2e-continue loader-container&quot;]</value>
      <webElementGuid>b00a516e-7cb7-4b79-afba-a77cf0cffe76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>b0258135-c1c6-4bb6-978d-1d8cc118f37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>ace1c891-e2c8-48dc-99a1-91b2dfc60cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Same as billing'])[1]/following::button[1]</value>
      <webElementGuid>38784b90-8eb5-4b95-9ce6-8f059696462d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='telerik-sales@progress.com'])[1]/preceding::button[1]</value>
      <webElementGuid>d984f1c9-8046-432a-8402-1ed46d9b3e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>de4d96b2-e702-4cfd-98ff-5df806067b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
        Continue
      ' or . = '
        Continue
      ')]</value>
      <webElementGuid>627cef59-b253-43d5-a17c-2e72da17d0fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
