<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3</name>
   <tag></tag>
   <elementGuidId>3716b457-a154-4506-bdde-39aafc498dbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c7728d44-4fad-4818-bdc5-2ad433cef0b4-3 > div.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c7728d44-4fad-4818-bdc5-2ad433cef0b4-3']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>334ccea2-d349-4aae-8437-51945b24ddda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>65f4641e-763b-4219-9bdf-1be7cfd75146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        3
      </value>
      <webElementGuid>94f35bf4-5544-4f57-9206-cfe40067deab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c7728d44-4fad-4818-bdc5-2ad433cef0b4-3&quot;)/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>07ac9058-1d70-48fe-8ab7-f98b000f3342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='c7728d44-4fad-4818-bdc5-2ad433cef0b4-3']/div</value>
      <webElementGuid>234399c5-d98f-488a-85f4-6eb67768939f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[1]/following::div[5]</value>
      <webElementGuid>a28cd908-2882-4362-829d-2e115211cffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Discounts'])[1]/following::div[10]</value>
      <webElementGuid>b668b311-77c2-46c5-8f7c-5c1aa895ceeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='telerik-sales@progress.com'])[1]/preceding::div[8]</value>
      <webElementGuid>9112f94c-b5b0-4643-8a2a-5cca01fadb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reload Page'])[1]/preceding::div[8]</value>
      <webElementGuid>c3a76399-a8ac-42e7-a061-1e0391e8e91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>18a4c61d-2687-42ca-a0b7-1bb56d0a3f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li[3]/div</value>
      <webElementGuid>559eda66-50ac-4a07-8233-e768cba04c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
        3
      ' or . = '
        3
      ')]</value>
      <webElementGuid>e912b875-947e-448f-96b0-8bb74d2cbe09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
