<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_biLastName</name>
   <tag></tag>
   <elementGuidId>ef1f5627-300c-42f3-bb1c-88c60ad40df2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#biLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='biLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23474e93-18fb-45cc-a56f-34da04435349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af0798ef-6b80-4f47-8a94-2e7ed9e9fa80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>biLastName</value>
      <webElementGuid>63ad695f-e9f4-4d83-967d-c73a9d116369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>biLastName</value>
      <webElementGuid>37852643-4c67-4674-9746-ffb8a88608eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0c779eac-72a4-414d-b740-b689f40b16af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>c8e29dc6-d502-4b69-a300-1e3736c76fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[^\/!@#\$%\^&amp;\*_\(\)\+=\[\]\\;\{\}\|:&lt;>\?\x22]+$/</value>
      <webElementGuid>413af5be-87cc-470f-95ca-5894d30313a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biLastName&quot;)</value>
      <webElementGuid>9d3b1d6f-0679-4abd-ab14-713cc54764d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='biLastName']</value>
      <webElementGuid>a2c263f8-f0cf-474b-b3b6-f9fbb56fc643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/input</value>
      <webElementGuid>05e5f25a-33e2-43ee-a28f-58b6ad54576c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'biLastName' and @name = 'biLastName']</value>
      <webElementGuid>4b0f56f9-486c-4d36-a18a-b3aeab6bb93f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
