<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_biAddress</name>
   <tag></tag>
   <elementGuidId>9beb0d81-40df-45c6-8702-d209f4dd6505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#biAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='biAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8150f852-9f1d-4dab-a165-abdc1f0f99fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>496b94cc-4896-4b82-93a8-fb96cb928768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>biAddress</value>
      <webElementGuid>6ca65284-6724-4123-87f4-26bfddd34d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>biAddress</value>
      <webElementGuid>05c68ac3-1681-4a21-97b6-d301f0245a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>cc90d8a1-1d18-4da4-b2a8-8cfd1e1171bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>f6b77dd6-4cb3-4243-b2a0-a856ce8069dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[^\[\]\{\}\|`&lt;>@_\$;~%\*\^_=\x22]+$/</value>
      <webElementGuid>4b0df54f-8f2b-48b1-98bb-e87c5bafb3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biAddress&quot;)</value>
      <webElementGuid>ac4b85c0-9add-4aec-a5de-a3b6bb4a62e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='biAddress']</value>
      <webElementGuid>679ac7d2-74f9-4515-ba4d-7aa73e32dba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>d462c36f-7f1f-4ee2-87e2-9cca506ef33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'biAddress' and @name = 'biAddress']</value>
      <webElementGuid>8d852b54-dfaf-475e-88a9-6a9b5d6aa652</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
