<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terms and Conditions_licenseAgreementLabel</name>
   <tag></tag>
   <elementGuidId>f83a972d-a85a-46de-ae15-5120607cf035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#licenseAgreementLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='licenseAgreementLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5acd0caa-ba48-4162-9c92-2b1dfb5fac20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d5f8ef43-5db0-45bd-b586-e11b42147a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseAgreementLabel</value>
      <webElementGuid>35936585-1bfa-492f-9c7a-c7b9cca770c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>1ff3db4a-3f00-4d59-b497-1d3f463ee3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licenseAgreementLabel&quot;)</value>
      <webElementGuid>48e4d6c5-b9aa-40be-bc6c-8da67b0bbdcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='licenseAgreementLabel']</value>
      <webElementGuid>7868f917-924b-424a-a021-2aaf55d2e6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6a0068d2-4b5e-4f58-aa2d-214e3aacc3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'licenseAgreementLabel']</value>
      <webElementGuid>ede484fd-c25b-47cf-8dcc-6daa4e4a9256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
