<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_biFirstName</name>
   <tag></tag>
   <elementGuidId>ee3fade2-2312-416d-b567-d5d3e17148d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#biFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='biFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8846cffd-34a8-41da-9db7-fa3624d5b58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2a742f7-577d-4392-86b3-1e309fe9758a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>biFirstName</value>
      <webElementGuid>f8b5d56f-bcbe-4fb0-b25b-2f82f6fea3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>biFirstName</value>
      <webElementGuid>321df89b-29f8-4f9d-baaf-61c0ad55bac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8360afff-101e-45b7-a63a-7fc1a904d38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9e62c532-3020-4e42-9183-196f98ce4e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[^\/!@#\$%\^&amp;\*_\(\)\+=\[\]\\;\{\}\|:&lt;>\?\x22]+$/</value>
      <webElementGuid>ac9e6940-ba2c-49a7-9a1e-292398d6e3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biFirstName&quot;)</value>
      <webElementGuid>113460a6-ce21-47c9-adf7-c480297e6bda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='biFirstName']</value>
      <webElementGuid>c74b396f-b702-4b16-b6a6-12d0af7808f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7a852154-b2fb-4d13-8d48-80dac2dc4097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'biFirstName' and @name = 'biFirstName']</value>
      <webElementGuid>4af57dc0-bbd3-4664-bd90-e6383adcc459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
