<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_biEmail</name>
   <tag></tag>
   <elementGuidId>995380ea-23cb-4e7a-b9cd-12b0254ef2ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#biEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='biEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45951d7f-5fc0-4053-8b80-165e25a5ceff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad18cafb-9bfb-4afe-bb7a-ce8ad1300b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>biEmail</value>
      <webElementGuid>2817f544-1fd5-4807-a66e-ff2c51d1a775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>biEmail</value>
      <webElementGuid>63932b91-044d-43a5-a61f-37fe716aec85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>ca395905-26c0-44f4-a8d3-c6bb55e0493c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>e3bff964-9286-4a55-ba72-3a55ab37ed16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[\w-\+\']+(\.[\w-\+\']+)*@[A-Za-z0-9]([A-Za-z0-9]|[-.][A-Za-z0-9])*\.[A-Za-z]{2,}$/</value>
      <webElementGuid>763c356e-0f52-4c50-8427-3bb1d971c706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biEmail&quot;)</value>
      <webElementGuid>13c3c75a-0933-43ed-af77-d6c20fe1cf15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='biEmail']</value>
      <webElementGuid>0004c444-03e0-4da6-a1bf-d696d1bda373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2a8e95e1-a5a1-4e30-b527-ee3c3f1a6c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'biEmail' and @name = 'biEmail']</value>
      <webElementGuid>267ea542-e614-463c-91ea-908d79c06249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
