<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__biZipCode</name>
   <tag></tag>
   <elementGuidId>a2e7c7f0-7c36-4e13-ab3b-cf31d872950f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#biZipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='biZipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33ae2b0f-8b8f-4dfb-9519-7a7ab577b12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac13a4e6-4a96-4550-a56b-976013c6b12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>biZipCode</value>
      <webElementGuid>b9c28978-6192-49b4-bd74-881988a849b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>biZipCode</value>
      <webElementGuid>282c90b2-0725-44f2-8da8-a7005ea4f2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2b44e01c-d322-4283-a67e-05836a864615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>311ec963-36fd-4552-bd69-82f189e41e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[a-zA-Z0-9\- ]+$/</value>
      <webElementGuid>6dcaf7c4-0d3a-4a7e-9b9e-f82ea83e0422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biZipCode&quot;)</value>
      <webElementGuid>2ab0170e-4ba1-46a3-bd12-d285c62a2f81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='biZipCode']</value>
      <webElementGuid>c72f48ad-094b-4f91-b87d-19d114dcfbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1241c787-b794-42fe-9f63-aa1207586ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'biZipCode' and @name = 'biZipCode']</value>
      <webElementGuid>6e4597df-21c9-42fc-9176-ccb347d19a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
