<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_biPhone</name>
   <tag></tag>
   <elementGuidId>3b899985-fdd3-4e57-bae4-08e9336b171e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#biPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='biPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f42952dd-60da-4cb3-962f-6578da88fae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64a70772-291f-4cad-b8dd-f4557b2240eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>biPhone</value>
      <webElementGuid>ab343cfc-47d2-4971-92b2-6307e7622cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>biPhone</value>
      <webElementGuid>40f89efb-ac2e-4b30-925f-526bd46b6f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>50a35f18-f344-4070-89d3-d7553afac241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>02107f40-1160-4229-94ad-d734973ca71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[a-zA-Z0-9#()\-\+\.\/\*\,\s]*$/</value>
      <webElementGuid>c7a28787-d2ad-419a-b2fa-ffc895c1d74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biPhone&quot;)</value>
      <webElementGuid>686984a3-e3d1-4332-9761-66bd5765a02b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='biPhone']</value>
      <webElementGuid>6348b827-277b-48b6-b432-ae50390330ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>eea64e62-0240-44ba-a502-8f7c834137ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'biPhone' and @name = 'biPhone']</value>
      <webElementGuid>5e9e9334-dcb7-4b9b-ac91-10ee7de342dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
