<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_biCity</name>
   <tag></tag>
   <elementGuidId>f3fe6b8e-6ed3-4b95-a642-9479b3cb0829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#biCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='biCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d72ed906-6e72-4c6a-bb29-7cc3c8fe0e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f4dcac3-32d4-4ba5-9c2a-8c970ad0eed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>biCity</value>
      <webElementGuid>e70c13e2-988f-471f-952b-555c5b80d9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>biCity</value>
      <webElementGuid>79a614f8-35f6-4d73-9b0e-c4b7bbcafa20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>85d605e7-6208-42e7-993b-7af948c3f307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>47aab84a-0db0-4c41-90b4-402cf4f5396a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[^\[\]\{\}\|`&lt;>@_\$;~%\*\^_=\x22]+$/</value>
      <webElementGuid>84e09e52-d166-4f75-910b-e78c43e2e272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biCity&quot;)</value>
      <webElementGuid>22dedb61-9dc2-4f4c-9741-fb689ada7f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='biCity']</value>
      <webElementGuid>0594f0ff-8355-49ea-92c4-ac2621e95c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>8cfceec3-ecd1-4ee7-8228-5d4d87a697e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'biCity' and @name = 'biCity']</value>
      <webElementGuid>d58365f4-5036-45f0-b30d-1976852ff0f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
