<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company_biCompany</name>
   <tag></tag>
   <elementGuidId>c2f0b8e7-64cf-4679-bd5d-9e2d0958eb77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#biCompany</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='biCompany']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62b563eb-2142-47ad-b620-4cff65b643bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dec0fcff-3fb7-4932-a098-7b51fb3bd12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>biCompany</value>
      <webElementGuid>dbeea34c-e4b9-4fa0-8569-d84597bb020c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>biCompany</value>
      <webElementGuid>ee04ff2a-a6ab-42f6-bc6a-824e80467601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>1140cc27-07ab-4820-92b0-a76303a8b568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>1d2a4dcb-245a-4cf1-b9b4-8423d47aca16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^(?!(-)|(\s+-))[^\[\]\{\}\|`&lt;>_\$;:~%\*\^_=\x22]+$/</value>
      <webElementGuid>bca9e807-6332-41ed-afee-dbc765fbef5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biCompany&quot;)</value>
      <webElementGuid>33d6907a-d8e7-4738-8298-45f11da2d564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='biCompany']</value>
      <webElementGuid>48244c41-d3ca-4480-9d45-8d2537261979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>005e0be0-e215-4e3c-ae59-ad99094b81ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'biCompany' and @name = 'biCompany']</value>
      <webElementGuid>dbd88b90-b3b9-4248-8e6c-f4e8d9dec842</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
