<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_American Samoa</name>
   <tag></tag>
   <elementGuidId>fe636067-929d-45d5-9273-81f4d9439856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e2948a4d-460a-43e2-9ea8-9191b4fb272f-as</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='e2948a4d-460a-43e2-9ea8-9191b4fb272f-as']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c487c393-640f-4bfe-9c8b-a5d5aa6d4afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3acf34ec-d4b9-4298-a9aa-77bc21c8e0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>eb6a7cc6-c023-41b8-94f4-d03e17e8f46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e2948a4d-460a-43e2-9ea8-9191b4fb272f-as</value>
      <webElementGuid>2203394a-d9e1-4b8c-8c13-ec90f39143a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3f8ccfd8-a41f-46b0-b85c-7e80c6597d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>602fec02-b9d3-4171-8bd1-a9ef880acd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>American Samoa</value>
      <webElementGuid>3cbd5133-8f19-473a-9dcb-10a2d8bed48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e2948a4d-460a-43e2-9ea8-9191b4fb272f-as&quot;)</value>
      <webElementGuid>c1775992-ab7b-49a8-92d7-ef8cacf202cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='e2948a4d-460a-43e2-9ea8-9191b4fb272f-as']</value>
      <webElementGuid>d26b3eb4-33d3-4b75-b38b-6da3c98c524d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='6d4fe969-09c0-4c88-a541-a5fec799ceef']/li[4]</value>
      <webElementGuid>9c2aa105-c1b6-4586-91d2-cf6a42b3a3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Algeria'])[1]/following::li[1]</value>
      <webElementGuid>80e638af-8ba7-40e8-ad2a-b22ce81ae816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Albania'])[1]/following::li[2]</value>
      <webElementGuid>42f40825-4f85-4866-9e87-32a36096af88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Andorra'])[1]/preceding::li[1]</value>
      <webElementGuid>f54116ae-f88a-4193-96ab-b95c4a8df8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angola'])[1]/preceding::li[2]</value>
      <webElementGuid>6e57f317-7c24-4865-9bf2-f3d3a4e09f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='American Samoa']/parent::*</value>
      <webElementGuid>44785295-5cfd-42f9-8a4b-c4dda547e518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li[4]</value>
      <webElementGuid>d98bc3e6-3623-44dd-a323-32cdaf9449a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'e2948a4d-460a-43e2-9ea8-9191b4fb272f-as' and (text() = 'American Samoa' or . = 'American Samoa')]</value>
      <webElementGuid>16b06b03-25d7-4d32-bf90-3b91f10ae14c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
