<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Country_k-select</name>
   <tag></tag>
   <elementGuidId>b4934dc6-3902-4aca-90db-2acdfdbca7ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//kendo-combobox[@id='biCountry']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>18ebf7dd-171c-4a8c-91ce-ce4305ba994f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>76c32be0-b201-42cc-bf53-da4a0a1168a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select</value>
      <webElementGuid>f2bb7e67-46cb-4fa6-a949-3c6caa3b5b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biCountry&quot;)/span[@class=&quot;k-dropdown-wrap k-state-default k-state-focused&quot;]/span[@class=&quot;k-select&quot;]</value>
      <webElementGuid>9a5985f3-1418-4b18-9b92-375428836da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-combobox[@id='biCountry']/span/span</value>
      <webElementGuid>73d58ea9-cf5b-4897-a8d8-da716827b016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country *'])[1]/following::span[2]</value>
      <webElementGuid>ccf49ed5-8eca-4624-b729-2e08416f86e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address *'])[1]/following::span[2]</value>
      <webElementGuid>a37ddaca-8e22-4fe3-95e7-1c64c2ea4da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City *'])[1]/preceding::span[2]</value>
      <webElementGuid>3154199a-c737-4bf4-b164-bd9967b0018d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-combobox/span/span</value>
      <webElementGuid>025340be-340d-451f-9fb3-9983021a65a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
