<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Quantity_k-icon k-i-arrow-s</name>
   <tag></tag>
   <elementGuidId>116f48b7-1b45-47c3-9d17-0620a59ab282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-icon.k-i-arrow-s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='k-549fe178-7095-419c-873c-6305711c3508']/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c08b5496-f619-4f38-806e-7820d275cb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>401a4c48-47fd-47ae-9d24-fa31860350a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-s</value>
      <webElementGuid>bd6ffabe-4aa4-43cd-8a61-5394b7216cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-549fe178-7095-419c-873c-6305711c3508&quot;)/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-s&quot;]</value>
      <webElementGuid>18df062e-90b0-4d2b-a89f-617c1287ef4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-549fe178-7095-419c-873c-6305711c3508']/span[2]/span</value>
      <webElementGuid>a63cbc6e-51f8-4338-95b4-a13676cd71a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]/span</value>
      <webElementGuid>f4cafd07-0190-4156-aafb-5ccbd7bc7b18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
