<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy  Get Registration</name>
   <tag></tag>
   <elementGuidId>1b547af7-3c30-40a3-9c57-f950bfce634f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-header-menu-links']/div/div/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b5b69cd-72ba-4731-a8e4-e98c6bec7f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d101243-583c-45f2-ba0f-3053ea334199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.incredible.co.za/buy-get-voucher</value>
      <webElementGuid>57f9b874-252e-4607-839c-bc06ab031dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy &amp; Get Registration</value>
      <webElementGuid>e09a6423-0ab4-4b16-967f-c1dd5e6539f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-header-menu-links&quot;)/div[1]/div[1]/div[1]/ul[1]/li[5]/a[1]</value>
      <webElementGuid>c6892f11-7f39-49be-86a2-ab359cbf39e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-header-menu-links']/div/div/div/ul/li[5]/a</value>
      <webElementGuid>c5e312d3-3be5-4f18-9396-fce1cc724a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Buy &amp; Get Registration')])[2]</value>
      <webElementGuid>c62f2c24-ccb0-4f0f-b0e9-9895638d91dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warranty Registration'])[2]/following::a[1]</value>
      <webElementGuid>55bb55ac-79f2-4a89-b282-2bccf10914cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support &amp; Services'])[2]/following::a[2]</value>
      <webElementGuid>b64f0d8f-cd7a-4b6a-a9ae-83f0f41f3f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store Finder'])[1]/preceding::a[1]</value>
      <webElementGuid>c7af148f-6d30-40b5-9841-054a815b02e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Track my Order'])[1]/preceding::a[2]</value>
      <webElementGuid>c689f7fe-f381-4007-a271-7f9824c7b784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.incredible.co.za/buy-get-voucher')])[2]</value>
      <webElementGuid>a7589b6c-edeb-4397-a252-f16a9f8626ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/ul/li[5]/a</value>
      <webElementGuid>867369d7-67cb-48ff-adc8-05ea07260bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.incredible.co.za/buy-get-voucher' and (text() = 'Buy &amp; Get Registration' or . = 'Buy &amp; Get Registration')]</value>
      <webElementGuid>9dfe85d0-637b-4abb-aa35-0b1181aa32ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
