<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This is a required field</name>
   <tag></tag>
   <elementGuidId>b52629ef-53f3-4ceb-8cbf-6232d25127d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#advice-required-entry-fieldHyd5vw155</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='advice-required-entry-fieldHyd5vw155']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4fbf9fd6-5191-4544-bd3b-235d34eed002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-advice</value>
      <webElementGuid>d9bfe49c-1843-4ae1-b010-b3966e567b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advice-required-entry-fieldHyd5vw155</value>
      <webElementGuid>d980b7a4-4995-4dfa-96c5-8ed9d3a90829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a required field.</value>
      <webElementGuid>ddd4ea27-0c2e-4325-a00b-8a876e566047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advice-required-entry-fieldHyd5vw155&quot;)</value>
      <webElementGuid>32fa6dfb-9541-4bca-9a6a-3c7284e8b534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='advice-required-entry-fieldHyd5vw155']</value>
      <webElementGuid>609217f8-adad-4d9d-8aa8-2ec12838b74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field_Hyd5vw155']/div/div</value>
      <webElementGuid>243d425b-797c-442e-b149-af531dfe3ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RSA ID / Passport Number'])[1]/following::div[2]</value>
      <webElementGuid>8ab9719e-287c-4252-82d8-902592a22936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::div[4]</value>
      <webElementGuid>e6e47402-5e66-4989-875c-071a087abf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::div[1]</value>
      <webElementGuid>7948db56-b3be-4518-b7f2-e61ee049ac6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a required field.'])[2]/preceding::div[1]</value>
      <webElementGuid>924784ab-6a58-4073-b2df-8f93250c6728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is a required field.']/parent::*</value>
      <webElementGuid>e8fc5ad5-6c11-4562-a47e-062436ae12c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/div/div</value>
      <webElementGuid>5d92d3e4-6b90-4656-b44a-a6a73413ccee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'advice-required-entry-fieldHyd5vw155' and (text() = 'This is a required field.' or . = 'This is a required field.')]</value>
      <webElementGuid>28759ed7-9125-423f-99fd-c6b787d9ca1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
