<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cookie and privacy policy_btn-cookie-allow</name>
   <tag></tag>
   <elementGuidId>cf0d6cbd-7fe4-4364-8098-32e5fe345be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-cookie-allow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btn-cookie-allow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35e35de6-78a9-4a8d-80b6-c537f50449bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-cookie-allow</value>
      <webElementGuid>197db808-36b5-470e-8b7c-4dd8d310cac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-cookie-notice</value>
      <webElementGuid>9303bd7c-a69f-4489-90b5-66a68b51d12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-cookie-allow&quot;)</value>
      <webElementGuid>002bdbb3-c362-4c0e-8132-e71f0e756a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btn-cookie-allow']</value>
      <webElementGuid>1605d8dc-c41a-4cc1-bd07-2dc3d545a816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notice-cookie-block']/div/div[2]</value>
      <webElementGuid>1ea1cdd5-b678-4ef3-8e5e-e1dd892e6f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>39114b5c-9eb4-42b9-9669-0bb40d6de7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btn-cookie-allow']</value>
      <webElementGuid>f2b2cb01-13f5-4923-902f-3767dee34b0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
