<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address_field152</name>
   <tag></tag>
   <elementGuidId>2fd45746-47e7-4889-8b43-903e7baa6d90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fieldHyd5vw152</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldHyd5vw152']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26a31028-c3fc-467f-95ed-07ffa4f685f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>380fa8a3-9440-4e93-82ce-f55155660a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field[152]</value>
      <webElementGuid>e449c662-3c0e-4bc9-9d78-7cb93a179303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldHyd5vw152</value>
      <webElementGuid>91f3e27b-a3b0-4000-a0b0-fd68b8313025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> required-entry input-text</value>
      <webElementGuid>27425a66-0a73-4ed1-9e74-63a710cb561f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_fieldHyd5vw152</value>
      <webElementGuid>ea413d6d-f6c1-4b0a-9eaf-534158154279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b82a2ed4-26b6-46a6-beb9-d12daa130de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldHyd5vw152&quot;)</value>
      <webElementGuid>198748c1-0aea-4762-b21d-d41704ad8c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldHyd5vw152']</value>
      <webElementGuid>79a4d8bf-6349-4a20-a9db-e67d7f8c6c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field_Hyd5vw152']/div/input</value>
      <webElementGuid>f7813f2f-0901-49e5-9ea4-0103cc5bef6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>0b732683-5abf-41e4-ba4d-dde794dccbd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'field[152]' and @id = 'fieldHyd5vw152']</value>
      <webElementGuid>8ed57a71-ec07-41ea-8530-64b79f70add6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
