<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail Address_field153</name>
   <tag></tag>
   <elementGuidId>acbf9047-d3eb-44b0-bae9-a02d55b85041</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fieldHyd5vw153</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldHyd5vw153']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e605f92-1ebf-4974-b36a-fa63043c096a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>75362c0a-10d5-40ff-9cf0-9c0de3c2ade1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field[153]</value>
      <webElementGuid>7c73b159-7e12-473a-96b1-ce8ac2e19a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldHyd5vw153</value>
      <webElementGuid>d405d8ea-a564-4910-80d9-796fd456774e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> required-entry validate-email input-text</value>
      <webElementGuid>2c69d136-264e-417c-b08a-457ca795c6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_fieldHyd5vw153</value>
      <webElementGuid>f96797e6-32c6-4189-acb4-842ce3da8e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>efae5811-28bf-4bef-8bb4-5913d7a216ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}</value>
      <webElementGuid>4fcca5f4-3f9f-4eac-b5ee-99f2a4773500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldHyd5vw153&quot;)</value>
      <webElementGuid>07ec7ab4-fb18-479b-8be6-e5b73d935731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldHyd5vw153']</value>
      <webElementGuid>910725cf-2fcc-44fb-818b-38edfc58d432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field_Hyd5vw153']/div/input</value>
      <webElementGuid>1a204698-80f1-4805-97c7-db4f34f69b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>96588966-2601-42c5-aced-93cd895c866d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'field[153]' and @id = 'fieldHyd5vw153']</value>
      <webElementGuid>9b46ac98-c5a0-48e0-a4bf-d04b479c9369</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
