<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CellPhone_field150</name>
   <tag></tag>
   <elementGuidId>1e9bd46a-ab1f-4540-9c00-de5a02d2c149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fieldHyd5vw150</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldHyd5vw150']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec481fec-0716-4ebf-959c-235134e82753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84e06bab-edae-4259-a429-07755d8f8889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field[150]</value>
      <webElementGuid>b2c12716-11a3-4ae7-af36-932fad489380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldHyd5vw150</value>
      <webElementGuid>8499103f-61da-48a5-a736-d842a7a7e39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> required-entry validate-length-min minimum-length-10 validate-length-max maximum-length-10 validate-field-150 input-text</value>
      <webElementGuid>a8956cd8-b3da-4ae6-b3c0-93e5b4571e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_fieldHyd5vw150</value>
      <webElementGuid>a8b5b4b3-3c54-497e-824f-87dfb06a798c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb28b590-c9fb-47d2-b657-f7d2dcb783d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldHyd5vw150&quot;)</value>
      <webElementGuid>3b3aa441-6cea-4ea5-ba75-f9e55ab0f900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldHyd5vw150']</value>
      <webElementGuid>f02ca9a2-afbe-41fd-bd69-0c43900bb4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field_Hyd5vw150']/div/input</value>
      <webElementGuid>24a7ddbe-1778-461c-bfec-3ccabaa7c050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>461f6526-11f3-4c63-b0b1-22553f64c933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'field[150]' and @id = 'fieldHyd5vw150']</value>
      <webElementGuid>4a23ab52-7fc2-43e7-a549-71011e6604cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
