<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2 days</name>
   <tag></tag>
   <elementGuidId>38688f82-e1fd-4425-8201-cd948966b29e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[18]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac5a8003-df09-4e50-b9de-a41e9831066e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>±2 days</value>
      <webElementGuid>3637fc68-ee3f-4441-b909-a890e987720e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1n6zj5y</value>
      <webElementGuid>0dd5ea4d-2f72-4014-861b-16ba05c53c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5bcd6920-dc0c-4739-8f40-3f8fe3a41083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d56f6213-6ed8-4a6f-9c12-0bfec7bf4d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43fc87c4-297e-4734-8d3c-cfa91311b948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 days</value>
      <webElementGuid>be91c264-9d61-4f07-a4ae-61ed161b58f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;micro-flex-chips&quot;)/div[@class=&quot;cizdcso h16bw5lk dir dir-ltr&quot;]/div[@class=&quot;c1a2lexk dir dir-ltr&quot;]/button[@class=&quot;_1n6zj5y&quot;]</value>
      <webElementGuid>9b33d6c9-fa17-4c8d-8437-efbdd2e2ac4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[18]</value>
      <webElementGuid>55c6f906-2a51-49fb-95e5-b30d94cd0843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='micro-flex-chips']/div[2]/div[3]/button</value>
      <webElementGuid>39699e6d-5b48-4bcd-9ada-b86ec6293b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exact dates'])[1]/following::button[2]</value>
      <webElementGuid>d1c495c4-108f-44b0-8e23-2397c09da81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flexible dates'])[2]/following::button[3]</value>
      <webElementGuid>f3aae714-61e7-4fcd-ab08-37e696806328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How long would you like to stay?'])[1]/preceding::button[3]</value>
      <webElementGuid>52a92b14-0967-4650-bfe9-5d4d6e8f224b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>457df7e3-9310-4a03-ad16-5929964dedf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '2 days' or . = '2 days')]</value>
      <webElementGuid>bfbcacc2-77c0-41fb-ae56-c9900883906f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
