<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_phoneInputphoneNumber</name>
   <tag></tag>
   <elementGuidId>0cfec853-8c3d-4b1f-8b7e-56331a29e37c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phoneInputphoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneInputphoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>647a335a-579a-44bc-b9a9-2d40463fb141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneInputphoneNumber</value>
      <webElementGuid>de89acf1-6c5e-428d-a14c-5872478c67e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fa0d35d-7ab3-4ea2-8cd2-4c288e9ad526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>login-signup-phonenumber</value>
      <webElementGuid>4275da5f-96c5-4363-8f0e-fd2ed21acb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1udbwkg focus-visible</value>
      <webElementGuid>8641e30f-5a03-41bf-a6f1-7bdb45b160c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneInputphoneNumber</value>
      <webElementGuid>1a33170e-672a-44d2-a9ad-a25d31f37841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel-national</value>
      <webElementGuid>86019ac3-2e88-499c-9d21-cf7adad76b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>f3bf83e8-05c8-4e8f-b465-1c8721ea4228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>03b78dad-b973-45c2-a29e-b3ff063a3c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>phone-number-help-text-phoneNumber airlock-inline-container</value>
      <webElementGuid>3799c7f9-e1be-478e-8189-b2f97b1131c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneInputphoneNumber&quot;)</value>
      <webElementGuid>106b366c-56e4-4e31-92c6-e73eb3c9b6a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneInputphoneNumber']</value>
      <webElementGuid>20d90cb8-017f-4afc-92d6-cea0fb73e4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8b114af8-8639-4363-ad74-f562cfc2e916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phoneInputphoneNumber' and @id = 'phoneInputphoneNumber' and @type = 'tel']</value>
      <webElementGuid>db24da4d-555c-4b57-ad56-6f00828075fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
