<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Where_query</name>
   <tag></tag>
   <elementGuidId>28a69769-83eb-41a5-801b-410a977fc1a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bigsearch-query-location-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ff3e54d-7a5d-469d-ba3e-ce86956ad50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ivycze5 dir dir-ltr focus-visible</value>
      <webElementGuid>f69f0ae4-774f-46a1-97f7-9e704bb64f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7715574c-816d-4b8e-b0f6-fe880a3c215e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8825d68e-c599-4fd3-bbe1-5337b705663e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9e713eef-3fce-4cd5-bc59-7df7c5ea9e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7429ff35-3cff-4c5a-aada-2884aee8c25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-input</value>
      <webElementGuid>20818bff-f908-4b81-abf1-2b8b68d1c647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>c2d9d14c-0ad3-46f2-9f84-a778be5450cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigsearch-query-location-description</value>
      <webElementGuid>ddb11d68-c840-4fc0-9bbe-b39fc4a53956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search destinations</value>
      <webElementGuid>96b11f68-c637-4724-a19e-c1f0bb3916a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>structured-search-input-field-query</value>
      <webElementGuid>b65b06a7-eb63-4166-b619-aa7d601bec35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigsearch-query-location-input&quot;)</value>
      <webElementGuid>df2cd152-634e-4257-9e10-42fb39ad18ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bigsearch-query-location-input']</value>
      <webElementGuid>0c6e6c11-d209-4847-a30f-eeee561572c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div/div/label/div/input</value>
      <webElementGuid>73e25831-8f5f-4754-8f6b-ee9bb0c84ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/input</value>
      <webElementGuid>41102ebd-16f2-488d-8690-761d4b257c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bigsearch-query-location-input' and @name = 'query' and @placeholder = 'Search destinations']</value>
      <webElementGuid>557b4e82-4d3d-4795-95cf-0f0f90f6a2e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
