<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Privacy Policy__kaq6tx</name>
   <tag></tag>
   <elementGuidId>ef6f787d-bbfe-4ffe-be7e-63d771dbab42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span._kaq6tx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e60b980e-ca02-4161-96d3-d7a3f736bcdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_kaq6tx</value>
      <webElementGuid>f0611fb7-51c3-445f-9954-02246a2f0f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scrollbar-gutter js-focus-visible&quot;]/body[@class=&quot;with-new-header&quot;]/div[13]/section[1]/div[@class=&quot;_vxvq8x&quot;]/div[@class=&quot;_z4lmgp&quot;]/div[@class=&quot;_z4lmgp&quot;]/div[@class=&quot;_1b64dznw&quot;]/div[@class=&quot;_12kfhdn&quot;]/div[1]/form[1]/div[@class=&quot;_1vk19cb&quot;]/div[@class=&quot;_1n35162&quot;]/button[@class=&quot;_6hkhatt&quot;]/span[@class=&quot;_jxxpcd&quot;]/span[@class=&quot;_kaq6tx&quot;]</value>
      <webElementGuid>dbbfcb7d-8fe1-43c2-aa16-5147598fac94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span/span</value>
      <webElementGuid>210e2e4a-2a5f-48c8-96d1-dbaeed608613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
