<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_1</name>
   <tag></tag>
   <elementGuidId>54031b96-472d-41aa-9a57-759cb182e4d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.i1h5tsj6.dir.dir-ltr > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='$170 per night'])[1]/following::*[name()='svg'][5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>cf699fe4-abea-4bf1-8878-5286621fc595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 32 32</value>
      <webElementGuid>1a3907b1-de75-4db0-b878-a3187ab51923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>74cbf91a-3ce7-476c-b1f1-f4221c843362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>334c74e2-f742-484f-9d68-7446f2e1eec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>28375b20-380d-419c-b744-df31e9fa37eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9cc1c865-056f-42d0-a07d-dd1340f57e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scrollbar-gutter js-focus-visible&quot;]/body[@class=&quot;with-new-header&quot;]/div[13]/section[1]/div[@class=&quot;_vxvq8x&quot;]/div[@class=&quot;_z4lmgp&quot;]/div[@class=&quot;_z4lmgp&quot;]/div[@class=&quot;_1b64dznw&quot;]/div[@class=&quot;_pa35zs&quot;]/button[@class=&quot;czcfm7x dir dir-ltr&quot;]/span[@class=&quot;i1h5tsj6 dir dir-ltr&quot;]/svg[1]</value>
      <webElementGuid>9757fbe1-896f-43b8-859c-ad5af166dbab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$170 per night'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>7016739b-d3cb-4c1a-8d79-d3a5f67774b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='night'])[20]/following::*[name()='svg'][5]</value>
      <webElementGuid>fbd2b3be-90ab-4638-a51c-5fe605dd00e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm your number'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>91e993a1-bca7-4d02-a7de-113e3a2863ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the code we sent over SMS to +244 923366180:'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>57a41b4c-ac99-440e-8cb9-8e7b46fad44d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
