<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payment</name>
   <tag></tag>
   <elementGuidId>04b3dc83-3571-4d52-bf95-1541d3e5f66d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#J6BB4C9 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='J6BB4C9']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f13f0630-39de-4f09-af0d-367f0f7f8657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/payment-options</value>
      <webElementGuid>0666f24a-e59e-4c05-8ea7-df39e576b2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment</value>
      <webElementGuid>93575c30-7fa5-4297-a2af-e759f9301ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html-body&quot;)/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;page-header-inner&quot;]/div[@class=&quot;header content&quot;]/div[@class=&quot;header content__right&quot;]/div[@class=&quot;header-trigger header-trigger__payment&quot;]/div[1]/div[1]/div[1]/p[@id=&quot;J6BB4C9&quot;]/a[1]</value>
      <webElementGuid>546701d0-de75-4ef0-8f87-01ccbe5a7a54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='J6BB4C9']/a</value>
      <webElementGuid>676343bb-5721-47d7-9b71-3afea622e465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Payment')]</value>
      <webElementGuid>2f634eb7-68e0-4b3c-a166-73600751fca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/following::a[1]</value>
      <webElementGuid>ef62e29b-70d0-4203-91b2-f5284cd3ea8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TVs'])[1]/following::a[2]</value>
      <webElementGuid>6985b876-15a1-40d3-b015-b4d37bcf5303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::a[1]</value>
      <webElementGuid>4f3fba4b-6f22-45e7-a2ac-16525f24f952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Star Gaming'])[3]/preceding::a[2]</value>
      <webElementGuid>d88d71ed-9ec7-4e57-8f20-ca5da9a458a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment']/parent::*</value>
      <webElementGuid>cdde510d-57b3-4bdc-a410-1d95effaae7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/payment-options')])[2]</value>
      <webElementGuid>57ddbcee-72e7-4478-ad2e-9900f2ebeb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>a658f6da-ae28-44cf-bfa5-0d041bef73ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/payment-options' and (text() = 'Payment' or . = 'Payment')]</value>
      <webElementGuid>59d00509-087c-4c02-9c25-1f944a11ac77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
