<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The ID number entered is not a valid So_319c78</name>
   <tag></tag>
   <elementGuidId>e2b51c60-b1f9-4f7f-a261-524f7b7048ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditApplicationForm__id_number-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='creditApplicationForm__id_number-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e4a5637-46c4-4f9f-b528-a3d1680bf4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>creditApplicationForm__id_number</value>
      <webElementGuid>0f809d6e-f371-4dbe-ac02-8715b70a0b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6aceb29-15e2-4420-b9c5-92ba0e193085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mage-error</value>
      <webElementGuid>4fd5be1d-9c43-42b6-90ec-9db6b7b734c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditApplicationForm__id_number-error</value>
      <webElementGuid>2d259869-469b-41b9-8511-e24d00c71a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The ID number entered is not a valid South African ID number.</value>
      <webElementGuid>193c9f05-aafa-4754-8563-b39a05ec0728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditApplicationForm__id_number-error&quot;)</value>
      <webElementGuid>8d4ad545-1c5b-4fb6-8035-b8ff707bc919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='creditApplicationForm__id_number-error']</value>
      <webElementGuid>6b89e8b4-44f4-42d6-9765-638f5d52c5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditApplicationForm.basicDetails__fieldset']/div/div[16]/div/div</value>
      <webElementGuid>6a690e82-c9b9-4bc5-b5cd-7eb4a038c20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South African ID'])[1]/following::div[2]</value>
      <webElementGuid>293dba1f-683c-4a6e-ba91-3814052e7de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Citizenship'])[1]/following::div[4]</value>
      <webElementGuid>3e8c2ed2-6c74-451f-99da-cceeb4e2f4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/preceding::div[1]</value>
      <webElementGuid>41c0b059-4b52-4e08-bb24-79b79565f5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::div[3]</value>
      <webElementGuid>de7a810d-8308-4b6c-8419-9aff689d3ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The ID number entered is not a valid South African ID number.']/parent::*</value>
      <webElementGuid>9ca7e70e-468f-4f9b-98f2-2f131442f27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div</value>
      <webElementGuid>08bc9ce1-ce24-46be-809c-d1485c48811d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'creditApplicationForm__id_number-error' and (text() = 'The ID number entered is not a valid South African ID number.' or . = 'The ID number entered is not a valid South African ID number.')]</value>
      <webElementGuid>bbfb940a-3623-4869-8de2-9356293a3d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
