<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Affordable Payment Options_pagebuilder-_f36f34</name>
   <tag></tag>
   <elementGuidId>5cc0abad-8c4b-49f1-aad2-2a5f66c95acd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > img.pagebuilder-mobile-hidden</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[3]/div/div/div/figure/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>49316739-e03e-4f76-9f55-3d9094916960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagebuilder-mobile-hidden</value>
      <webElementGuid>3299a731-ed7c-4f06-9739-ce46e021ad49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.incredible.co.za/media/wysiwyg/1_3_page_CTA-Apply_Online_1.png</value>
      <webElementGuid>78ffb9bf-aca2-436b-8254-d8d105101603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.incredible.co.za/media/wysiwyg/1_3_page_CTA-Apply_Online_1.png</value>
      <webElementGuid>7fd48c46-ccce-4d7c-8daf-eaedbe6e6bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-above-the-fold</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>60adf0c6-24df-4339-866c-b454a8ce710c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element</name>
      <type>Main</type>
      <value>desktop_image</value>
      <webElementGuid>646cde39-e8e9-49ac-ae81-b3a17e032596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pb-style</name>
      <type>Main</type>
      <value>EHTIDXO</value>
      <webElementGuid>979d4fb1-8441-45af-9988-7f8e9c6a206c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>04658fb5-20c6-4b61-91a0-3490b25ac096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[3]/div[1]/div[@class=&quot;pagebuilder-column-group&quot;]/div[@class=&quot;pagebuilder-column&quot;]/figure[1]/a[1]/img[@class=&quot;pagebuilder-mobile-hidden&quot;]</value>
      <webElementGuid>73cd98d9-d7c0-474a-9921-0a9fa76cc8b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[3]/div/div/div/figure/a/img</value>
      <webElementGuid>42b12644-bd91-4371-bad3-b0d1222914b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.incredible.co.za/media/wysiwyg/1_3_page_CTA-Apply_Online_1.png')]</value>
      <webElementGuid>4509c15b-4168-45f7-9d95-c823b0019486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/a/img</value>
      <webElementGuid>88123c6e-fada-4b18-ac20-cdcbca19246b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.incredible.co.za/media/wysiwyg/1_3_page_CTA-Apply_Online_1.png']</value>
      <webElementGuid>dab72db9-4a19-469a-a6f5-79fc07e3d3b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
