<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_South African ID_id_number</name>
   <tag></tag>
   <elementGuidId>382d7007-341e-49e4-beb1-51b666a9580a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditApplicationForm__id_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditApplicationForm__id_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>067abd47-6707-43c2-84ca-01c94aceb15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c53e9400-963e-4c49-8bfc-368e208b03bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>c7211b58-5690-4b5e-93ea-101dbae553ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                   attr: $parent.getAttributes(field.value, {
                       title: field.value.label,
                       id: $parent.getId(field.key),
                       name: field.key,
                       placeholder: field.value.placeholder,
                       autocomplete: field.value.autocomplete
                   }),
                   value: $parent.prepopulateField(field.key)
               , afterRender: $parent.fieldReady.bind($parent)</value>
      <webElementGuid>05a10881-87dd-4544-9fcd-8e897c3c6b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dob</name>
      <type>Main</type>
      <value>date_of_birth</value>
      <webElementGuid>08cdad4e-daf8-4710-adcf-6f6a6e671e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>South African ID</value>
      <webElementGuid>dafe0976-5473-474f-819c-d22987d08a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditApplicationForm__id_number</value>
      <webElementGuid>b1fc3e97-cb87-4e23-bc0f-251724f1fd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_number</value>
      <webElementGuid>362f84ef-0cc5-4da3-8ccc-5ae20289ea5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f93a1517-6fa3-4db8-85eb-19528616718a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{&quot;validate-sa-id-length&quot;:true,&quot;validate-sa-id-pattern&quot;:true,&quot;required&quot;:true}</value>
      <webElementGuid>ac3a8c4e-c50e-4638-814f-85fe59e19f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate-default</name>
      <type>Main</type>
      <value>{&quot;validate-sa-id-length&quot;:true,&quot;validate-sa-id-pattern&quot;:true,&quot;required&quot;:true}</value>
      <webElementGuid>0b2b4783-e9fc-4e4a-a8e8-cbbf665322d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditApplicationForm__id_number&quot;)</value>
      <webElementGuid>b217df77-467b-4ba6-b539-8075e6c31bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditApplicationForm__id_number']</value>
      <webElementGuid>f1f48bc2-5fa4-42a7-b494-4102a0363a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditApplicationForm.basicDetails__fieldset']/div/div[16]/div/input</value>
      <webElementGuid>9a2919a8-e064-4bfa-b578-df45a0b5f2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/input</value>
      <webElementGuid>cabb93b2-9ee9-4afa-b0f0-6e2c98a5662e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'South African ID' and @id = 'creditApplicationForm__id_number' and @name = 'id_number']</value>
      <webElementGuid>703fd47e-5708-4cfa-a8c5-d216505cb451</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
