<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Initials_initials</name>
   <tag></tag>
   <elementGuidId>c05584a3-c5c7-40ea-a108-2b9c28d9bbb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditApplicationForm__initials</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditApplicationForm__initials']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>579ea290-689b-471d-9ca8-2bec0347a42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>280c4103-0b1b-4aef-aa91-d589bc948db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>a661defc-59d2-4968-9db2-8576cbe157a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                   attr: $parent.getAttributes(field.value, {
                       title: field.value.label,
                       id: $parent.getId(field.key),
                       name: field.key,
                       placeholder: field.value.placeholder,
                       autocomplete: field.value.autocomplete
                   }),
                   value: $parent.prepopulateField(field.key)
               , afterRender: $parent.fieldReady.bind($parent)</value>
      <webElementGuid>03222b53-7f9a-419f-b787-07d6ff1f3b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-firstname</name>
      <type>Main</type>
      <value>first_names</value>
      <webElementGuid>57a38a18-a074-41c7-a564-16cdea8d6c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lastname</name>
      <type>Main</type>
      <value>surname</value>
      <webElementGuid>094a384b-24a6-49b9-bd48-0d9f4b45fd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Initials</value>
      <webElementGuid>8544afaf-1092-42ce-bd75-ccaf5234af33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditApplicationForm__initials</value>
      <webElementGuid>d143030c-31b8-4774-822a-0a3784eae84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>initials</value>
      <webElementGuid>a2332542-f279-4d26-a139-67841401e510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9104c653-11ed-4f45-9ecf-d0652d73c872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{&quot;required&quot;:true}</value>
      <webElementGuid>6fe46228-b89a-41a9-84d6-0ea65450df57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate-default</name>
      <type>Main</type>
      <value>{&quot;required&quot;:true}</value>
      <webElementGuid>b305610a-611b-44fd-bc88-eced9a4f35ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditApplicationForm__initials&quot;)</value>
      <webElementGuid>ba9b0e71-f362-4788-b149-07a8a2f1e744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditApplicationForm__initials']</value>
      <webElementGuid>29792724-9ff3-4433-bc15-5ca60a7915a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditApplicationForm.basicDetails__fieldset']/div/div[10]/div/input</value>
      <webElementGuid>f698d9d8-165a-4842-b698-5f55cadbd3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>95697f26-d4d4-4640-a0ed-e109da34e4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Initials' and @id = 'creditApplicationForm__initials' and @name = 'initials']</value>
      <webElementGuid>51beb309-f5ed-4996-90a2-53bdbe5007f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
