<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log in Now</name>
   <tag></tag>
   <elementGuidId>db904404-de49-4e9d-9db7-0839e1d83e63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-accent.u-w100.loader-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>633ca3b4-7df3-44db-8db3-5877a82c3c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ad20fa75-7308-497e-b368-871b1d954a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>trackevent</name>
      <type>Main</type>
      <value>Form events, form.captcha, started</value>
      <webElementGuid>347f6836-922c-4cc3-a232-456acdda90aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-accent u-w100 loader-button</value>
      <webElementGuid>72853584-8485-49da-834d-aab311975c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in Now</value>
      <webElementGuid>77e00729-db80-4cd1-b08a-06cbb712f400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app-body&quot;]/app[@class=&quot;app-content&quot;]/ng-component[1]/div[@class=&quot;u-pr&quot;]/loader[@class=&quot;u-pa&quot;]/div[@class=&quot;loader-content&quot;]/div[@class=&quot;container-floating flow-container&quot;]/div[1]/form[@class=&quot;form-field-list u-mb15 ng-dirty ng-valid ng-touched&quot;]/div[@class=&quot;u-mb15&quot;]/button[@class=&quot;btn btn-accent u-w100 loader-button&quot;]</value>
      <webElementGuid>ebae8a8b-5de0-4b5f-ae14-8e6448d21f61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>658f8447-212b-41b9-8289-5cf723c718c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep me logged in'])[1]/following::button[1]</value>
      <webElementGuid>e9950617-9afa-48a1-af62-42a4b02da345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>1ba0dc1d-58cf-4c79-89d4-3862d09632d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recover it now.'])[1]/preceding::button[1]</value>
      <webElementGuid>82f603cb-951d-42ba-80e7-18ce348dff12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log in Now']/parent::*</value>
      <webElementGuid>ad0a928f-35a4-496b-b207-3b33f1456826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a6ab066a-6a9a-4aa9-8ea5-24c9127db367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Log in Now' or . = 'Log in Now')]</value>
      <webElementGuid>8942c831-782f-4ec1-8885-4d34cf2aa7c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
