<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_first-name</name>
   <tag></tag>
   <elementGuidId>e9254ce0-0bf4-41ce-a9e3-8bfe021fa070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fist-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fist-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a062acb-7b1a-46a5-86ce-390e1e9f12bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fist-name</value>
      <webElementGuid>b63d3533-fb1d-471f-ba6d-ca116cbc8b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>first-name</value>
      <webElementGuid>355ff5b4-8f4c-431a-9ca0-2aa54e938452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ba442ee-499a-441b-a3e0-9b576e43a7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>afce7663-543e-4b7c-9166-d526bfe58ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>d5917236-da58-4496-9a4f-b9c0483db1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[^!@#\$%\^&amp;\*_\(\)\+=\[\]\\;,./\{\}\|:&lt;>\?\x22]+$/</value>
      <webElementGuid>5e84c3cf-eab7-4c0f-895e-2f476d3de3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fist-name&quot;)</value>
      <webElementGuid>f7b04fcf-4b6b-4fdb-8a0b-98755f8c1a8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fist-name']</value>
      <webElementGuid>ea5c45eb-178d-4cee-844f-18c2f293c9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[3]/div/input</value>
      <webElementGuid>a67a6d7e-2c5f-461b-81fd-5cc8fe34227f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ca161c43-d9df-4b8d-8cd0-9edf9629c06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fist-name' and @name = 'first-name' and @type = 'text']</value>
      <webElementGuid>1f677da5-3ffb-4a21-9335-e2e37cbc10ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
