<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To assign you to a local team that ca_2c75fe</name>
   <tag></tag>
   <elementGuidId>3aaa1424-ec5d-4935-aba9-45ede08174c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-1ce4153e-d5f0-4890-9c91-f9ce4bb89859</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='k-1ce4153e-d5f0-4890-9c91-f9ce4bb89859']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90a2b4cd-f4b2-4898-bfce-a323b7b015f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ef9a841c-b84e-4ca8-866d-935a570f401a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ecb47ff4-4f80-47cd-8712-06d6ab716bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>e9d5938d-b8b9-4bb6-a07d-5aa796ae8036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ce9bf3df-fcaf-4a64-8550-712590bff734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea48c1f5-d388-448b-a622-95dc213713fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>6474b097-15e5-4219-add3-9f314cdc858d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-1ce4153e-d5f0-4890-9c91-f9ce4bb89859</value>
      <webElementGuid>65238682-44f1-4dfc-bd85-dda0a7e55f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>34836e36-f001-4c81-a4c3-68a1f3aee550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f7618d59-2290-4fee-a2ab-c308285e4bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>68f3eee1-6cdf-4030-9994-57886dd17f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>bfbd16ea-0168-4732-a150-69bcc072f82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f062f3c0-795e-498b-92f0-9325696852a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ef9b35d9-a4f6-4c8a-9969-194887844804</value>
      <webElementGuid>90d10304-9f29-4845-9a6d-e5219b08493a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-1ce4153e-d5f0-4890-9c91-f9ce4bb89859&quot;)</value>
      <webElementGuid>6cc8fdd8-3ed4-41b5-a296-1fa18dda4e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-1ce4153e-d5f0-4890-9c91-f9ce4bb89859']</value>
      <webElementGuid>937bd2b5-4e72-481d-99fe-38780efef854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-combobox[@id='country']/kendo-searchbar/input</value>
      <webElementGuid>622d0f66-5415-4ca3-af4a-38896d4528a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-searchbar/input</value>
      <webElementGuid>22e2f18f-2fdd-4e9f-a5b9-a5fb91f3634f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-1ce4153e-d5f0-4890-9c91-f9ce4bb89859' and @placeholder = 'Select']</value>
      <webElementGuid>05cac6f3-8b52-4e71-b4d2-44c6dbcd46a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
