<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Angola</name>
   <tag></tag>
   <elementGuidId>f1f130b1-fcaf-4a45-9550-e08edfe1e236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#8ee4b4f3-f76a-4283-a10d-5dee9e55d5e1-Angola</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='8ee4b4f3-f76a-4283-a10d-5dee9e55d5e1-Angola']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b90c4438-5a6a-40ef-b1e2-74157e8d2d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ec33ef58-47b1-4c16-ba37-cc7372bd960a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item</value>
      <webElementGuid>e290f0b8-c674-4fbe-8d40-36acf3276e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8ee4b4f3-f76a-4283-a10d-5dee9e55d5e1-Angola</value>
      <webElementGuid>e10c7890-0528-4596-a019-8fb430179e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2581ff1c-1697-45b0-aed4-c88528c2cf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5549829f-53ef-4975-b9d8-38b9de0be6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Angola</value>
      <webElementGuid>e90493c9-721b-478f-a86f-629fb475aa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8ee4b4f3-f76a-4283-a10d-5dee9e55d5e1-Angola&quot;)</value>
      <webElementGuid>00d79491-ea47-4dc5-8002-4526fa442dc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='8ee4b4f3-f76a-4283-a10d-5dee9e55d5e1-Angola']</value>
      <webElementGuid>c64c627b-2b6b-4363-bd90-e131a47cad87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ef9b35d9-a4f6-4c8a-9969-194887844804']/li[6]</value>
      <webElementGuid>9ab7fe35-066b-489a-a0eb-f4891018ef9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Andorra'])[1]/following::li[1]</value>
      <webElementGuid>789afea2-35f1-48a8-bde8-5f5264bce8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='American Samoa'])[1]/following::li[2]</value>
      <webElementGuid>2a5495b6-a146-41a3-996f-5d4d49f7a942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anguilla'])[1]/preceding::li[1]</value>
      <webElementGuid>c5ed334f-2859-41dd-8ce6-ca1fd98136b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]</value>
      <webElementGuid>0567e05d-8c37-4094-9558-61cb6c7a8bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '8ee4b4f3-f76a-4283-a10d-5dee9e55d5e1-Angola' and (text() = 'Angola' or . = 'Angola')]</value>
      <webElementGuid>632ec222-15e6-47aa-b5b6-181bfbebbece</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
