<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_To assign you to a local team that can_cabbee</name>
   <tag></tag>
   <elementGuidId>809f0040-545c-4686-b950-329ac358d9b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-button-icon.k-icon.k-i-caret-alt-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//kendo-combobox[@id='country']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d6128031-b4f2-48af-834d-96f49f5ee58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button-icon k-icon k-i-caret-alt-down</value>
      <webElementGuid>2899c93f-315e-4ad3-8fa6-1c45504e8266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;country&quot;)/button[@class=&quot;k-input-button k-button k-icon-button k-button-md k-button-solid k-button-solid-base&quot;]/span[@class=&quot;k-button-icon k-icon k-i-caret-alt-down&quot;]</value>
      <webElementGuid>ea5c2944-b17a-45a8-bb7e-24b63f24c586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-combobox[@id='country']/button/span</value>
      <webElementGuid>73d1c262-eb49-4377-89fd-c0edaef68c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>a5d0046d-d131-4377-8a3f-e744cbb4b111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
