<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privacy Policy</name>
   <tag></tag>
   <elementGuidId>6d40268d-8c96-434d-959e-55283dae8a0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-footer-accordion']/div[2]/div/div/div[2]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1bf9fc35-6371-4509-80a2-db1aaade1da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.incredible.co.za/services/privacy-policy</value>
      <webElementGuid>387f8c07-03e1-4db8-8d09-556424662897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy Policy</value>
      <webElementGuid>acb73210-8304-4208-9653-5ad0a956b7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-footer-accordion&quot;)/div[@class=&quot;footer-list-container&quot;]/div[@class=&quot;row-full-width-inner&quot;]/div[1]/div[@class=&quot;collapsible-list&quot;]/ul[1]/li[4]/a[1]</value>
      <webElementGuid>2a0903e9-e718-49c8-8918-b4b29050a707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-footer-accordion']/div[2]/div/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>eba0141a-bd04-4733-862c-fcdf7213ffbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Privacy Policy')]</value>
      <webElementGuid>b745e99d-ac17-420a-8173-3b9cb7715671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotional Terms &amp; Conditions'])[1]/following::a[1]</value>
      <webElementGuid>6f2fe008-74e3-4d25-9ff2-6733fbd2cb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Terms &amp; Conditions'])[1]/following::a[2]</value>
      <webElementGuid>c606c2de-fa7b-451a-bf52-b73674a28dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do More Foundation'])[1]/preceding::a[1]</value>
      <webElementGuid>1810be9a-1126-44d5-83ff-cf68424e2f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abacus Insurance'])[1]/preceding::a[2]</value>
      <webElementGuid>1af54f28-cd69-4786-8eef-caa09b5232f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Privacy Policy']/parent::*</value>
      <webElementGuid>e43b8dcd-bcda-46ee-bd19-4a2faf636712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.incredible.co.za/services/privacy-policy')])[2]</value>
      <webElementGuid>59d9139e-dede-4965-99fa-8162a0b53938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>e79621c5-889e-4435-b2cd-fd6d9a19b96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.incredible.co.za/services/privacy-policy' and (text() = 'Privacy Policy' or . = 'Privacy Policy')]</value>
      <webElementGuid>0069710c-b240-4c02-a02d-166e82483369</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
