<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sitefinity</name>
   <tag></tag>
   <elementGuidId>b13aeb28-2715-4f51-8439-b227643df435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_C002_Col00']/div/div/div[2]/ul[4]/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7226351-98a5-4952-98a2-001292ee156a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/support/sitefinity</value>
      <webElementGuid>3b16bb2b-bc05-46d6-bcb4-9031d5641932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sitefinity</value>
      <webElementGuid>3a7c5a00-fe8d-4ba2-94b0-451020cb9adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_C002_Col00&quot;)/div[@class=&quot;sfContentBlock&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-4 u-small-mb0&quot;]/ul[@class=&quot;List Space--cozy u-ff-sans1 u-fs20 u-mb5 u-m-mb3&quot;]/li[1]/a[1]</value>
      <webElementGuid>7d590ddb-268f-40e9-913a-794b3e951ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_C002_Col00']/div/div/div[2]/ul[4]/li/a</value>
      <webElementGuid>729c4602-e48d-4db1-8b23-08c2c44f1a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Sitefinity')])[2]</value>
      <webElementGuid>e8e43aae-2518-4c63-b924-8593fcf996a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CMS'])[2]/following::a[1]</value>
      <webElementGuid>5d3fa895-c798-45be-a748-b1f2d07cc95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Studio'])[2]/following::a[1]</value>
      <webElementGuid>4e77489a-66f3-42d4-b7ed-db1604882965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UI/UX TOOLS'])[1]/preceding::a[1]</value>
      <webElementGuid>42262d3e-164b-49f1-9c44-6e3e634d1eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ThemeBuilder'])[2]/preceding::a[1]</value>
      <webElementGuid>fffc66fb-0c50-4637-a0a3-9615e3b93124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/support/sitefinity')]</value>
      <webElementGuid>0e6e8383-5713-46d9-9be9-82098eec54d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li/a</value>
      <webElementGuid>6bcfb9f9-ebd1-4266-a198-18b2db0abc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/support/sitefinity' and (text() = 'Sitefinity' or . = 'Sitefinity')]</value>
      <webElementGuid>f4898608-6a52-4571-a44a-2cfe07f8810c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
