<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get A Free Trial_js-tlrk-nav-drawer-button</name>
   <tag></tag>
   <elementGuidId>845180fd-3f91-4943-81f4-0f9878c384ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-tlrk-nav-drawer-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js-tlrk-nav-drawer-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43fa68a8-da89-43b5-84ea-32fe96f8d8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ed2aca1-eedc-4fbf-8e0f-88d8a8608f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>df32e016-8f6c-4596-8296-b00c2619782d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TK-Aside-Menu-Button TK-Aside-Menu-Button--Toggle-Drawer</value>
      <webElementGuid>58996122-ff23-49e0-8d62-784a7ccc61fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-tlrk-nav-drawer-button</value>
      <webElementGuid>abee20f2-9cd0-4bd4-86dc-0ca14390805f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-tlrk-nav-drawer-button&quot;)</value>
      <webElementGuid>ed71ad64-2617-4602-af79-97afac16b704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js-tlrk-nav-drawer-button']</value>
      <webElementGuid>fcd16697-39a9-47e1-9158-be6436b54d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='js-tlrk-nav']/section/div/div[3]/ul/li/button</value>
      <webElementGuid>039b2a4a-814d-4be9-acca-594df391c211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get A Free Trial'])[1]/following::button[1]</value>
      <webElementGuid>287a76f6-fb58-4b69-814a-b3150f0ede8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::button[1]</value>
      <webElementGuid>ce10db5e-b9dd-4de2-8c0e-dd8565c91634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close mobile menu'])[1]/preceding::button[1]</value>
      <webElementGuid>4d2a86f7-f623-42b9-8664-f094b2e5f956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demos'])[2]/preceding::button[2]</value>
      <webElementGuid>5dfa2c97-3d30-4b64-86ef-6b57d052be1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/button</value>
      <webElementGuid>17fe1419-fc8b-471c-8596-74f273180d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'js-tlrk-nav-drawer-button']</value>
      <webElementGuid>dbeb9caa-516b-4fc8-84e6-e8f1f50dfed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
