<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Components</name>
   <tag></tag>
   <elementGuidId>091913f8-ffd9-4235-8e94-1ada23c5f833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-in.k-state-hover.k-state-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='page-tree_tv_active']/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0d3232d6-d98f-403f-b45c-36ee1f6d259c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-in k-state-hover k-state-focused</value>
      <webElementGuid>adf726c7-cc91-46db-86fc-58ffc36cb6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Components</value>
      <webElementGuid>c599b495-f16e-4b66-a262-f2a7dcb4c1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-tree_tv_active&quot;)/div[@class=&quot;k-mid&quot;]/span[@class=&quot;k-in k-state-hover k-state-focused&quot;]</value>
      <webElementGuid>80e2f0ad-809b-48a5-ac2b-1899f6ea368c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='page-tree_tv_active']/div/span[2]</value>
      <webElementGuid>95f8c37a-bec8-4f48-8907-f0546134595c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Getting Started'])[1]/following::span[2]</value>
      <webElementGuid>9b17c685-75a5-4b92-9fe2-ca9d1ea7d006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduction'])[1]/following::span[4]</value>
      <webElementGuid>91baca9b-c71b-4535-b0eb-09f30a742dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shared Utilities'])[1]/preceding::span[2]</value>
      <webElementGuid>3fc0a633-6e03-4487-b18f-534a57a5d853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Styles &amp; Appearance'])[1]/preceding::span[4]</value>
      <webElementGuid>39504db8-cd10-4246-8b3d-3bb35113c6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Components']/parent::*</value>
      <webElementGuid>02576c99-7638-4e4e-9aa4-774e479c81bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span[2]</value>
      <webElementGuid>a8a3e7b1-396c-4e60-a995-7d7861b04781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Components' or . = 'Components')]</value>
      <webElementGuid>f9cd7ada-3784-4686-85ca-7e32166b8b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
