<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create an Account</name>
   <tag></tag>
   <elementGuidId>f4ee8774-d109-430f-984b-944d1bc9d936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.action.tertiary.registration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='header-slideout--1']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>141ab5eb-9658-4630-82ed-e645f03d7a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action tertiary registration</value>
      <webElementGuid>50c7dddd-c82d-4b7e-ab9c-958934483b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.incredible.co.za/customer/account/create/</value>
      <webElementGuid>41119d6c-35b2-40e3-853b-5666dc36fa61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create an Account</value>
      <webElementGuid>59d867b0-61e8-413c-974e-ba2409acf62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-slideout--1&quot;)/div[@class=&quot;registration-container&quot;]/a[@class=&quot;action tertiary registration&quot;]</value>
      <webElementGuid>f56f4ab0-798b-4a03-85c5-55a2b6ef28d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='header-slideout--1']/div[2]/a</value>
      <webElementGuid>b1914a60-bd55-4436-8fdf-98585a4607bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create an Account')]</value>
      <webElementGuid>b55e14eb-ed84-4ed8-9635-be016e5e6200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View and track your orders.'])[1]/following::a[1]</value>
      <webElementGuid>97eb6d8e-ef47-4fda-8050-1201b6b19085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store multiple delivery addresses.'])[1]/following::a[1]</value>
      <webElementGuid>39c2ce1b-537f-4419-a0dc-a3386569cd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/preceding::a[1]</value>
      <webElementGuid>f3e35935-b58a-41b3-885e-efbf0966e742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/preceding::a[1]</value>
      <webElementGuid>980c4b7a-529b-42ee-8a94-dff056d2045e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create an Account']/parent::*</value>
      <webElementGuid>7ce8d989-1aac-4076-85b4-25bc9e1a920a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.incredible.co.za/customer/account/create/')]</value>
      <webElementGuid>4b166d58-6073-4bab-a417-ee6e45af1771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div[2]/a</value>
      <webElementGuid>f8c8d6cc-e3a4-4c3c-a3db-84fbfedff1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.incredible.co.za/customer/account/create/' and (text() = 'Create an Account' or . = 'Create an Account')]</value>
      <webElementGuid>0b16ec44-c42d-4a64-88fc-1287c909bbc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
