<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cellphone Number_cellphone_number</name>
   <tag></tag>
   <elementGuidId>40d8ff4e-4e11-497f-9ccc-f4a45e1d837c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cellphone_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cellphone_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1802a0b-0341-4136-b3ff-b2dd47c4ea8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a4506fee-63b8-4e5b-a7f6-8e18ea4c3629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cellphone_number</value>
      <webElementGuid>ee0d6799-c8f7-4c9b-98ba-28e4e03df6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cellphone_number</value>
      <webElementGuid>9bf01997-7b36-47ce-81a8-cf88480ee675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cellphone Number</value>
      <webElementGuid>cdfd6b89-1c3e-4ea5-8ecd-12f34635389c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>30b464ba-f822-4d2e-9dba-cd75c48fadcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{'required': true, 'validate-phoneLax': true}</value>
      <webElementGuid>f544d60a-69b2-43ca-b386-d9ae1830936c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>866c163d-c54c-484e-9e45-d6d9afc56957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>515c29c0-8b17-4497-8291-97d294b6becf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cellphone_number&quot;)</value>
      <webElementGuid>90cf81c5-a754-44cb-b82c-d1b94e9d2118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cellphone_number']</value>
      <webElementGuid>909a4bcb-45fd-4e73-a8dd-072d7eef19b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset/div[3]/div/input</value>
      <webElementGuid>a24b1610-3c90-42ca-bfed-f074b8b9b84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>00a19ede-1b8c-42bb-bb3d-99f8b65aee23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'cellphone_number' and @name = 'cellphone_number' and @title = 'Cellphone Number']</value>
      <webElementGuid>f8a7c5e4-15e9-4ea4-b169-0395471fd779</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
