<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice Order Number_field13</name>
   <tag></tag>
   <elementGuidId>197e1562-29d6-4b0f-a6c9-d7222ecaa009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fieldOmUXQF13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldOmUXQF13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cb5558a-634e-4a1e-871e-fbc5be5653bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b56d5e6b-d216-4fbb-a6a9-714003374f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field[13]</value>
      <webElementGuid>c75de2ac-f4fe-4b59-b1e8-533de822dd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldOmUXQF13</value>
      <webElementGuid>271bec13-9d5a-4850-b56a-8b8a133e928b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> required-entry input-text</value>
      <webElementGuid>cf8301c7-c976-42bf-b0f4-aed69bab207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_fieldOmUXQF13</value>
      <webElementGuid>64671e76-4901-4a8e-82fc-a447438efa75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>70509e73-2b77-4bab-b712-69c74050129e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldOmUXQF13&quot;)</value>
      <webElementGuid>e67aae7e-75ed-45dc-9af8-661f834776c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldOmUXQF13']</value>
      <webElementGuid>05a8c271-fcae-467c-aa65-e9c67ac513aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field_OmUXQF13']/div/input</value>
      <webElementGuid>8dfd0bbb-bdde-4e70-9e14-0fa32ac0f136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input</value>
      <webElementGuid>36f353dd-24d8-4a59-b745-3c0eb969dbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'field[13]' and @id = 'fieldOmUXQF13']</value>
      <webElementGuid>12027542-5c27-421d-8dd8-0a7a1bcb9a01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
