<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail Address_field5</name>
   <tag></tag>
   <elementGuidId>718fdfa4-6709-4068-af07-9ed466b3c764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fieldOmUXQF5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldOmUXQF5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40704a2e-d2fc-44c2-b7f1-9f87e9ad78bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9810e521-17bd-48ee-aff3-9b7aa431ba75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field[5]</value>
      <webElementGuid>2648dc90-186f-4d2f-83da-9c32f57b0344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldOmUXQF5</value>
      <webElementGuid>4cc6ed3e-6826-4fab-8579-07b69858965a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> required-entry validate-email input-text</value>
      <webElementGuid>ffcb5d89-dd93-46cc-b3b1-34ba571c67e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_fieldOmUXQF5</value>
      <webElementGuid>54a8b133-d2a5-45a7-a133-0c3ef27fbc45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9892358a-5e7e-4555-8ba2-0356c7f94738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}</value>
      <webElementGuid>1e277d4b-7cc8-45bc-9d7d-19d4a9fe1264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldOmUXQF5&quot;)</value>
      <webElementGuid>c7ea5a05-6a28-4690-84ea-c63276bc3780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldOmUXQF5']</value>
      <webElementGuid>74242d15-eb6e-459c-88d6-53860f1eb09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field_OmUXQF5']/div/input</value>
      <webElementGuid>064b36c0-9477-4ca1-9442-b1f4f3fa227d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>be161e10-eb26-4974-ae96-26423a9af0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'field[5]' and @id = 'fieldOmUXQF5']</value>
      <webElementGuid>f6b9f31b-6680-4317-b47e-dde9cad4bbfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
