<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Brand and Model_field18</name>
   <tag></tag>
   <elementGuidId>2cc8b9bf-a232-42a5-8fdb-7e7f4f53a1b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fieldOmUXQF18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldOmUXQF18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0011f94-a56c-4713-8af2-0a746844769a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5e0deb5-460f-46a7-8a30-512cfb597b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field[18]</value>
      <webElementGuid>ee2eb714-d5b6-43e2-b420-f93374e8890f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldOmUXQF18</value>
      <webElementGuid>150020cc-09bd-4b9d-b82e-b0df0afbefb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> required-entry input-text</value>
      <webElementGuid>f21c3b48-008c-4eb0-a2ac-35e5c54c6774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_fieldOmUXQF18</value>
      <webElementGuid>c22176af-50d2-44bf-ba62-c64aba821bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddea3c63-f35f-4468-812a-3b1a4e5dfcb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldOmUXQF18&quot;)</value>
      <webElementGuid>877bae53-dd66-4307-86b7-8834c7259712</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldOmUXQF18']</value>
      <webElementGuid>4a1c1e53-8602-4ca7-9ed0-18c1c3d7ad2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field_OmUXQF18']/div/input</value>
      <webElementGuid>521a5242-5b01-43a3-8122-70320699ef4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/input</value>
      <webElementGuid>026bbba4-736a-46bd-ac6e-86b0674a399e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'field[18]' and @id = 'fieldOmUXQF18']</value>
      <webElementGuid>1b45341c-a8fd-4c07-b434-5486f64074c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
