<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_eye-icon</name>
   <tag></tag>
   <elementGuidId>73675ed1-a527-48d5-b0f6-11e62f0cceec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='eye-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eye-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>11a68762-c3f0-474e-b3d1-ea5090356905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>showPassword();return false</value>
      <webElementGuid>c0565476-63ee-414f-afdc-b066492e82ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseup</name>
      <type>Main</type>
      <value>showPassword();return false</value>
      <webElementGuid>dc6a4413-35dd-4f57-bced-a97780ea8130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eye-icon</value>
      <webElementGuid>d5db929d-cca4-4321-b804-f792d32256a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show-pass fa fa-eye fa-lg</value>
      <webElementGuid>5acfb7da-6d39-4955-aa33-e1230001e3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eye-icon&quot;)</value>
      <webElementGuid>77d71265-9e44-4b3e-8e72-7f26c8bedfe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='eye-icon']</value>
      <webElementGuid>fc0866b8-6243-41de-8df2-e96747043c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/main/form/div/div[2]/i</value>
      <webElementGuid>3dc382f7-4fb1-4488-8802-e9591e7a1978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>9e7911b4-b64c-4e58-ae71-a8ba31881dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'eye-icon']</value>
      <webElementGuid>9689743a-61df-4b31-879a-9e0501944623</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
