<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Adicionar_Isencao</name>
   <tag></tag>
   <elementGuidId>c09935fd-a768-439f-b81b-53426ed20f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='formExemptionModal:submitModal']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>11e6bffe-5648-4c1b-907e-d13dcb0ff38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>328301d6-be61-44b7-b674-c4a003affd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adicionar</value>
      <webElementGuid>1c14fa31-9e0e-4646-a16d-f8c1f977410e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formExemptionModal:submitModal&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>7fc7f697-483b-4d2c-81fb-0f3beea8cf84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='formExemptionModal:submitModal']/span[2]</value>
      <webElementGuid>a8e1ac4e-5660-4e0b-a7c0-6931bdad631a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::span[2]</value>
      <webElementGuid>f9076389-0896-4cc6-8e4f-b0cf91529276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OIC imóveis próprios (IP Renda)'])[2]/following::span[11]</value>
      <webElementGuid>76fdba68-58b1-419c-abac-b4b1d56f359f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anexar Documento'])[1]/preceding::span[1]</value>
      <webElementGuid>442527b7-e554-4b3e-a9c3-d8b7edd4dee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Documento*'])[1]/preceding::span[2]</value>
      <webElementGuid>06db72ae-4c3d-492c-8ce9-f42bf7446299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/div/div/button[2]/span[2]</value>
      <webElementGuid>633e2e59-587a-4725-b875-37412e35874e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Adicionar' or . = 'Adicionar')]</value>
      <webElementGuid>ad02a78a-a71b-4bd8-bf6a-3b449b904273</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
