<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Adicionar_Titular</name>
   <tag></tag>
   <elementGuidId>61a7c8ed-7e11-4652-b4e6-f52870ac06d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='formRegisterOwnerModal:btnAdicionar_Register_Owner']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6aa12765-6048-4295-8ee3-2596c1d24d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>4f1d1859-43ca-4848-8722-f54c97eaee63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adicionar</value>
      <webElementGuid>28000ad9-6808-4327-bbfb-92bdecb0c81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegisterOwnerModal:btnAdicionar_Register_Owner&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>6b39f021-3fea-4003-a987-a44dce135122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='formRegisterOwnerModal:btnAdicionar_Register_Owner']/span[2]</value>
      <webElementGuid>6d6f7c66-fc8f-4f81-afa7-aaf334bea971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/following::span[2]</value>
      <webElementGuid>554dd058-c7ba-4a39-a8a2-42f51194a5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome/ Denominação do Proprietário*'])[1]/following::span[4]</value>
      <webElementGuid>16db384c-9c30-497f-b5f6-f4f05dd37637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caro Utilizador'])[2]/preceding::span[1]</value>
      <webElementGuid>6965edac-52a5-419e-b912-035bdfc7be23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motivo de Rejeição'])[1]/preceding::span[3]</value>
      <webElementGuid>970eca17-7aa2-466d-8c35-8a49ece1bdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button[2]/span[2]</value>
      <webElementGuid>e8dd8315-c21a-4bd3-b6be-838598a0b30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Adicionar' or . = 'Adicionar')]</value>
      <webElementGuid>d4139342-1de0-4b4a-866a-c957c0e8c299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
