<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero do Artigo Matricial Fsico_frmPa_938dc0</name>
   <tag></tag>
   <elementGuidId>0b47863a-85f4-4780-9def-94c7c4ed5f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:phicialMatricialNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19b77898-62da-4ddc-a4cb-3770afcafcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:phicialMatricialNumber</value>
      <webElementGuid>3390c128-de47-4ea5-8cb5-7b6ef96f7b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:phicialMatricialNumber</value>
      <webElementGuid>3bc6fe26-f313-4fe2-84f5-7fdf670fda02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1222e1d-37fc-4de2-9e72-ffb1b859a992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all full-width ui-state-focus</value>
      <webElementGuid>6c899b02-b04f-4ccc-aa3c-d9d1d773a12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>11bc96a2-0d33-41de-bcb8-6536a95fc12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2160742f-4348-4d55-a32f-78237765b5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ea6e13c-fbfa-40ab-ba62-2b3c71b85e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:phicialMatricialNumber&quot;)</value>
      <webElementGuid>893b323d-1447-43b5-ae4d-8df55ce31303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:phicialMatricialNumber']</value>
      <webElementGuid>c3ba1693-798e-4787-9e4e-e58899b0903f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPatrimony:tvSuporte:accPrincipal:j_id_75']/div/div[4]/div/input</value>
      <webElementGuid>4859746c-832b-4254-b51a-6350ce15b306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>6c82636f-d748-49f4-898c-9dfb8cfac64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPatrimony:tvSuporte:accPrincipal:phicialMatricialNumber' and @name = 'frmPatrimony:tvSuporte:accPrincipal:phicialMatricialNumber' and @type = 'text']</value>
      <webElementGuid>4b6d35f3-4b1a-4300-bbad-8558ea709a65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
