<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Valor Declarado (Kz)_frmPatrimonytvSuporteaccPrincipaldeclaredValue_input</name>
   <tag></tag>
   <elementGuidId>897bc601-6edb-47f6-99e4-48f70578d74f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>746fdb7d-2044-4d96-b425-d59b56db4766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:declaredValue_input</value>
      <webElementGuid>8a4f96cd-3c28-4224-acc7-cafeeca88a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:declaredValue_input</value>
      <webElementGuid>4a77c9d9-a7c8-4545-a13c-57a7f227279f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aed66706-c5c6-4b81-a633-6d03defc2c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8033dbb7-8585-4c18-a9e3-b6308132eb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;frmPatrimony:tvSuporte:accPrincipal:declaredValue&quot;,e:&quot;valueChange&quot;,p:&quot;frmPatrimony&quot;,u:&quot;frmPatrimony&quot;});</value>
      <webElementGuid>223442cf-fa10-4fc3-bc4a-08a225783978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>9591b85a-5850-4dd4-b8fd-57a61b9aecb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-con</name>
      <type>Main</type>
      <value>javax.faces.BigDecimal</value>
      <webElementGuid>a6cbc1c4-e949-42f1-a0d4-40b8ebab2ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-hl</name>
      <type>Main</type>
      <value>inputnumber</value>
      <webElementGuid>1d6cfa57-62b9-4e85-91bb-f96fd234861a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>56ccee2a-eca6-45a3-9171-b15893147f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7735c89b-f3b6-418f-b4da-d8fb106348b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>194f03bf-14cb-4074-99b4-ff80eb4550f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:declaredValue_input&quot;)</value>
      <webElementGuid>53d717c2-b4b8-4985-bedb-74445efe94c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue_input']</value>
      <webElementGuid>cffd3d33-2679-4a6c-a309-6b72f7d04aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue']/input</value>
      <webElementGuid>5a9c7801-68e4-403a-b532-ac6ef628f351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[8]/div/span/input</value>
      <webElementGuid>e452661d-a712-486b-86a7-79d45cff3bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPatrimony:tvSuporte:accPrincipal:declaredValue_input' and @name = 'frmPatrimony:tvSuporte:accPrincipal:declaredValue_input' and @type = 'text']</value>
      <webElementGuid>e6bdbb0b-de67-4cef-b1db-1c23fc63dbd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
