<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIF_frmPatrimonytvSuporteaccPrincipal_f4d3f6</name>
   <tag></tag>
   <elementGuidId>2ca3ffba-5764-405b-bdc0-1e50ddbbc354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:taxpayerDetails-nif']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>742f5e37-c3d2-4bee-ad10-01d0b19eb3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:taxpayerDetails-nif</value>
      <webElementGuid>2ff72de5-8b5e-4666-b202-4bbdb5bbbfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:taxpayerDetails-nif</value>
      <webElementGuid>d4931c0b-a1c0-43d5-84c9-cc796f8b2a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22988917-8e2c-4717-a453-59267f619f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;frmPatrimony:tvSuporte:accPrincipal:taxpayerDetails-nif&quot;,e:&quot;blur&quot;,p:&quot;frmPatrimony:tvSuporte:accPrincipal:taxpayerDetails-nif&quot;,u:&quot;frmPatrimony:tvSuporte:accPrincipal:pngDeclarant frmPatrimony:messages frmPatrimony:tvSuporte:accImovel:ownerTaxOfficeSelect frmPatrimony:tvSuporte:accImovel:ownerProvinceSlct frmPatrimony:tvSuporte:accImovel:ownerMunicipalitySelect frmPatrimony:tvSuporte:accImovel:ownerCommuneSelect&quot;});</value>
      <webElementGuid>f297e94f-4a1b-4367-8716-11a1613ba8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all full-width ui-state-hover ui-state-focus</value>
      <webElementGuid>f5c26e94-72d0-4277-a21a-61b8b7a9e1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a7313d3d-60c6-4524-b9a0-e6145b26c893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd897265-045f-4052-ba8d-66551ef81efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7bca5f1e-ffc4-462c-9056-6da62ab9a165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:taxpayerDetails-nif&quot;)</value>
      <webElementGuid>bf237adb-e478-4c14-b648-5bfb3618df67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:taxpayerDetails-nif']</value>
      <webElementGuid>a0121d90-75af-45cc-89b5-e54c237cac33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPatrimony:tvSuporte:accPrincipal:pngDeclarant']/div/div/input</value>
      <webElementGuid>30f0a8fb-2462-438f-a316-50e3203fbc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/input</value>
      <webElementGuid>ecc02c83-e947-48e1-9e8e-59b2eaa81323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPatrimony:tvSuporte:accPrincipal:taxpayerDetails-nif' and @name = 'frmPatrimony:tvSuporte:accPrincipal:taxpayerDetails-nif' and @type = 'text']</value>
      <webElementGuid>1921893f-f4f4-44ca-8385-5c51494e1a5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
