<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIF_formRegisterOwnerModalpropertyownernif</name>
   <tag></tag>
   <elementGuidId>4eae5045-295c-4337-9a06-e177d6e47c17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formRegisterOwnerModal:propertyownernif']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fa3e5b6-3bdd-493a-ad09-78f3fcd50193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formRegisterOwnerModal:propertyownernif</value>
      <webElementGuid>774105c1-cb3f-4140-a1aa-c4aef239ea92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formRegisterOwnerModal:propertyownernif</value>
      <webElementGuid>efd236ff-07fe-4175-9d78-8f1dfaa82a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8471bc84-f849-49ca-ab1c-ef6fbdad03eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;formRegisterOwnerModal:propertyownernif&quot;,e:&quot;valueChange&quot;,p:&quot;formRegisterOwnerModal:propertyownernif&quot;,u:&quot;formRegisterOwnerModal:nameofowner formRegisterOwnerModal:messagesOwnerModal formRegisterOwnerModal:propertyownernif&quot;});</value>
      <webElementGuid>18a8f76a-4fb7-4a79-8a4d-78c523a4a607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all full-width ui-state-focus</value>
      <webElementGuid>7041b0bb-6fd9-479d-a02e-c106ba12aab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>960cd8ff-4ca9-4473-9534-a10ef6010de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>931325ac-ecae-440b-afe8-62c4636b0ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ca41a079-d1f1-4af8-abed-3b4271e99da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegisterOwnerModal:propertyownernif&quot;)</value>
      <webElementGuid>376c5743-b26c-4ac7-9101-b16a6430d12a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formRegisterOwnerModal:propertyownernif']</value>
      <webElementGuid>8e6c7a76-3150-46a3-aeaa-cd04dab1bbb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='formRegisterOwnerModal:pngRegisterOwnerModal']/div/div/input</value>
      <webElementGuid>2a033232-6a83-40c7-88ee-22bebeeeadfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span/div/div/input</value>
      <webElementGuid>90d4c80a-9b5f-4fed-aeac-171caa41d77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'formRegisterOwnerModal:propertyownernif' and @name = 'formRegisterOwnerModal:propertyownernif' and @type = 'text']</value>
      <webElementGuid>df91d353-62fa-4598-a50a-cd06f03e225b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
