<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Proprietrio</name>
   <tag></tag>
   <elementGuidId>1b029b39-1c8f-4b14-9100-47a25584da92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmPatrimony:tvSuporte:accPrincipal:behalfOf_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3da7c8f6-eb5e-4aa5-adb5-49f9bb3e9f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>47d42056-deaa-4b57-aba4-9014ffe62b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Proprietário</value>
      <webElementGuid>4dce05f9-ec41-4925-a567-0b1012cea1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9647679c-a054-46c1-a6f6-4bbc9cd12462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>024fe69e-a42a-484f-a200-b886d45be36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:behalfOf_1</value>
      <webElementGuid>3fc07050-85dd-4e06-b034-079dc1482652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proprietário</value>
      <webElementGuid>b38523c6-2962-46dc-a02f-ec7387f40e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:behalfOf_1&quot;)</value>
      <webElementGuid>1bfd1210-5fcd-48d2-a200-a0be0e544a8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmPatrimony:tvSuporte:accPrincipal:behalfOf_1']</value>
      <webElementGuid>4aff8006-4afb-46e0-b716-f6b89cfba48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='frmPatrimony:tvSuporte:accPrincipal:behalfOf_items']/li[2]</value>
      <webElementGuid>46d7d64d-eb18-41f7-bb2e-8914446fc8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não preenchido'])[12]/following::li[1]</value>
      <webElementGuid>0c571e64-d95d-422d-8a37-c941ce7023b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exploração Mineira'])[2]/following::li[2]</value>
      <webElementGuid>4b9e8e25-5682-4595-a6b3-1ac6a31bbe65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usufrutuário'])[4]/preceding::li[1]</value>
      <webElementGuid>1174aea3-a238-4cfb-9daa-f5d3050e5a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superficiário'])[4]/preceding::li[2]</value>
      <webElementGuid>988e5ee5-3850-48a4-ad2e-6b4716750814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/ul/li[2]</value>
      <webElementGuid>f5196594-3bda-4f33-a368-330d4b952c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmPatrimony:tvSuporte:accPrincipal:behalfOf_1' and (text() = 'Proprietário' or . = 'Proprietário')]</value>
      <webElementGuid>f0540dd5-4b9f-4937-a14f-2c9ba53fc5de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
