<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Proprietrio_1</name>
   <tag></tag>
   <elementGuidId>41a5c9f9-e7d5-44f3-ba87-ca00a0c15bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='formRegisterOwnerModal:patrimonyOwnerType_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6dc03863-d36c-4905-8292-69b86cc1457e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>681c5fe5-011b-443c-8962-4f51bf2302a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Proprietário</value>
      <webElementGuid>14b36445-b7d5-44a3-bb0e-f19c77f992ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>db3e6fcf-4424-45d7-9480-81171a12646d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>89ae0e26-1bbe-44f1-afe2-1818bd477cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formRegisterOwnerModal:patrimonyOwnerType_1</value>
      <webElementGuid>461d142f-829d-4ba8-938e-dea5a703af7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proprietário</value>
      <webElementGuid>475add2b-962b-4591-852f-a9744d7b691b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegisterOwnerModal:patrimonyOwnerType_1&quot;)</value>
      <webElementGuid>50e5d63b-ac21-403f-ba6d-0f1d7adcf01a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='formRegisterOwnerModal:patrimonyOwnerType_1']</value>
      <webElementGuid>f740dee9-5435-41af-b335-eaf1c3537319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='formRegisterOwnerModal:patrimonyOwnerType_items']/li[2]</value>
      <webElementGuid>c6703ad9-da9f-495c-8b8b-8ae628e180f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não preenchido'])[10]/following::li[1]</value>
      <webElementGuid>1987cebe-f69b-4b8c-9d5d-1d2209d8ca5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não preenchido'])[9]/following::li[2]</value>
      <webElementGuid>1ed1150b-424c-4dee-8dae-57f02276621a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usufrutuário'])[3]/preceding::li[1]</value>
      <webElementGuid>6a09b5eb-52ea-4912-b7b3-650ea452b0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superficiário'])[3]/preceding::li[2]</value>
      <webElementGuid>1e141c95-6be8-4127-b3d8-3e449a5be269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[4]/div/div/div[4]/div/ul/li[2]</value>
      <webElementGuid>3b11da29-61dd-4081-afb3-61e0c6821340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'formRegisterOwnerModal:patrimonyOwnerType_1' and (text() = 'Proprietário' or . = 'Proprietário')]</value>
      <webElementGuid>c346531e-2591-495a-8131-2d5304843cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
