<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Responsvel_ui-chkbox-icon ui-icon ui-i_39efb1</name>
   <tag></tag>
   <elementGuidId>ba3fe7e2-2be1-407a-99b5-ca29e3f451ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formRegisterOwnerModal:responsible']/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default.ui-state-hover > span.ui-chkbox-icon.ui-icon.ui-icon-blank.ui-c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3b17c40c-fb1a-4015-a28b-f3346021ece6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-chkbox-icon ui-icon ui-icon-blank ui-c</value>
      <webElementGuid>55bd2f06-1811-48fe-acfa-d33a71800cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegisterOwnerModal:responsible&quot;)/div[@class=&quot;ui-chkbox-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]/span[@class=&quot;ui-chkbox-icon ui-icon ui-icon-blank ui-c&quot;]</value>
      <webElementGuid>332d7ffa-5ed1-46b1-845e-5310ed5f2dd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formRegisterOwnerModal:responsible']/div[2]/span</value>
      <webElementGuid>b3db1aa0-60dc-4f1a-bb81-7ff91e3c678a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[3]/div/div/div[2]/span</value>
      <webElementGuid>045b8ea9-2975-4ad2-9472-b41fbcd2bf8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
