<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Prdio</name>
   <tag></tag>
   <elementGuidId>446932a7-7985-4727-94d6-aa1fbbcd71ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='submenu-register-patrimony']/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.submenu.patrimonio > a.collapsed > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>94513fdb-7bf0-4f18-8f38-a1c7e14b90ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Prédio</value>
      <webElementGuid>e09e0c77-1b4f-4542-996e-f9e34b4ec49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-register-patrimony&quot;)/li[@class=&quot;submenu patrimonio&quot;]/a[@class=&quot;collapsed&quot;]/span[1]</value>
      <webElementGuid>58f3dca2-6297-445d-af23-5504f8a4c021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='submenu-register-patrimony']/li[2]/a/span</value>
      <webElementGuid>e2ef5b88-2e78-4be5-bd23-dfe3e5023f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesquisar'])[1]/following::span[1]</value>
      <webElementGuid>ed7ebfeb-a884-4487-8632-a5990e8e8d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastro'])[1]/following::span[2]</value>
      <webElementGuid>f1999988-6d94-48d0-9934-d2baa2e3e181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urbano'])[1]/preceding::span[1]</value>
      <webElementGuid>2a26e04f-b3ce-4ffb-a2d4-26f12dcb5aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propriedade'])[1]/preceding::span[2]</value>
      <webElementGuid>af8dba74-f1ca-4fb9-84ad-ff0eb697ea12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prédio']/parent::*</value>
      <webElementGuid>3164eb36-66b4-44b9-841b-6acac0bec3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/ul/li[2]/a/span</value>
      <webElementGuid>51a91d37-86c7-481b-8584-d4a99ded259d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Prédio' or . = ' Prédio')]</value>
      <webElementGuid>01ec7f4c-3d6e-4671-a3bf-144b647bab52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
