<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rstico</name>
   <tag></tag>
   <elementGuidId>0d54c080-0f3a-4975-a43d-29edfa3cf924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='submenu-register-predio']/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d4913504-c18d-47ca-b19b-fd36c78fdd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rústico</value>
      <webElementGuid>d36413d0-4219-4e69-8c87-e0aaad3cdbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-register-predio&quot;)/li[2]/a[1]/span[1]</value>
      <webElementGuid>a0e1fb96-3e6c-49a3-8d83-6de25b2de467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='submenu-register-predio']/li[2]/a/span</value>
      <webElementGuid>cfc99b89-a43a-4385-98fe-dab8e40a7c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propriedade Total'])[1]/following::span[1]</value>
      <webElementGuid>8e513b32-5ae9-40d5-8071-467975fcb583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horizontal'])[1]/following::span[2]</value>
      <webElementGuid>0ebc26c4-a1cb-4d93-99d0-26de150e4d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fracção'])[1]/preceding::span[1]</value>
      <webElementGuid>45b59119-11b3-48f8-88f4-72e7f151f5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pré-Cadastro Electrónico'])[1]/preceding::span[2]</value>
      <webElementGuid>f986ee4b-894c-4f27-807b-23b4e73b426d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rústico']/parent::*</value>
      <webElementGuid>5d89143c-85a7-484c-b61c-8dcf23a436ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/ul/li[2]/a/span</value>
      <webElementGuid>baa542ac-924d-4fa2-8328-f90360b94538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rústico' or . = 'Rústico')]</value>
      <webElementGuid>7e9ed17a-f760-4076-b7a2-89c72c91808b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
