<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Qualidade de Cultura_frmPatrimonyt_e92def</name>
   <tag></tag>
   <elementGuidId>38050c8d-3a5c-496e-bdd1-ede5c91dd0c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='frmPatrimony:tvSuporte:accPrincipal:cultureQuality']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>243d57ca-26bb-4269-a588-ac8cdcec9e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:cultureQuality</value>
      <webElementGuid>c7242302-51a0-4b29-91c0-b28f9dad5b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:cultureQuality</value>
      <webElementGuid>730e1631-83ff-4c1c-bf7d-8f6b1237d051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>5af87701-0738-40e9-87f4-db8c5e5a03ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>62b23f4a-c26e-4b4e-ba1a-7d75fd3c46ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d6991ce8-a293-4a6f-a073-22a6a165d92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtextarea ui-widget ui-state-default ui-corner-all form-control ui-inputtextarea-resizable ui-state-hover ui-state-focus</value>
      <webElementGuid>0d58a1d7-048b-4994-b437-97ec66ae9190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>aadb5d65-7181-4519-bfd0-1432d0750072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1f769c72-1d43-445f-9bfc-d627c2d46a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2bfa9042-4872-42a9-a8e2-38a0f7f9e2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6782088f-8095-4723-89fc-2b9c735fc591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autosize-on</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d2f0a7d-f36a-4233-a976-276faa3d1172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:cultureQuality&quot;)</value>
      <webElementGuid>c7301e58-3e3b-4089-95cc-64e2b7ef2d85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='frmPatrimony:tvSuporte:accPrincipal:cultureQuality']</value>
      <webElementGuid>9366e35e-532e-4352-bd57-5645988cd208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPatrimony:tvSuporte:accPrincipal:j_id_4h']/div/div[6]/div/textarea</value>
      <webElementGuid>fa554a97-1df1-454c-b0f6-92335ca566a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>986a63bf-3663-4996-88b0-69f788b644ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'frmPatrimony:tvSuporte:accPrincipal:cultureQuality' and @name = 'frmPatrimony:tvSuporte:accPrincipal:cultureQuality']</value>
      <webElementGuid>3ce14457-bba8-4c4c-bd6c-94cb4fb21b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
