<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>39adde7d-6b56-45e7-8830-83284c408434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;show more&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='klevu-show-opt-category']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fdbc5b1c-1077-415c-8f4e-c9513263e86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:klevu_filters.showAll('klevu-filter-box_category');</value>
      <webElementGuid>32dd020a-15cd-47f3-9926-c4aa87f560d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>show more</value>
      <webElementGuid>a28213b5-0100-44a2-9281-5ebd8704146c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>90c541c6-8af7-4369-8240-d00020d80ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;klevu-show-opt-category&quot;)/a[1]</value>
      <webElementGuid>ad35bd09-eb1b-4bc4-a82a-4995f9688b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='klevu-show-opt-category']/a</value>
      <webElementGuid>979cf955-d5b8-4286-a8ee-799c6ef89b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='connected home'])[1]/following::a[1]</value>
      <webElementGuid>a393840c-25e3-4c88-9a2b-10695ecf92d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='branded pages'])[1]/following::a[2]</value>
      <webElementGuid>e9981dd8-096f-4e44-ac89-01b597f15d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRAND'])[1]/preceding::a[2]</value>
      <webElementGuid>e76f1258-510f-455f-a2d7-adcb787a85f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='apple'])[2]/preceding::a[3]</value>
      <webElementGuid>f374e729-8f0f-45e0-8dec-3240c3b178bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:klevu_filters.showAll('klevu-filter-box_category');&quot;)]</value>
      <webElementGuid>f1f53d52-0e9a-478e-94b2-72d088266c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>16458064-520e-4e41-8092-839bc427edbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:klevu_filters.showAll(&quot; , &quot;'&quot; , &quot;klevu-filter-box_category&quot; , &quot;'&quot; , &quot;);&quot;) and @title = 'show more']</value>
      <webElementGuid>b25df8e8-b1d4-4f18-9cfe-e7c03a516290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
