<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_iphone</name>
   <tag></tag>
   <elementGuidId>803dac12-f055-481d-9362-c9614a334ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.klevu-pt-rs-keywords > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='klevu-pt-hover-box']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9e1fcfa-71ac-4e1c-8b88-c8d474372f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:klevu_search.getResultsForClickedTerm( 'iphone', 'ps' );</value>
      <webElementGuid>c1046516-aab6-417d-be3d-83f190e84682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>0a3bb4f8-572a-4788-aa87-8d27c328b6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iphone</value>
      <webElementGuid>0f63a64b-b78e-4e1d-b610-3de1faa3642c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;klevu-pt-hover-box&quot;)/div[@class=&quot;klevu-pt-rs-keywords&quot;]/a[1]</value>
      <webElementGuid>b5cb8d4d-5629-4c26-806a-c613463dd21e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='klevu-pt-hover-box']/div/a</value>
      <webElementGuid>c4ca635c-723b-42b7-bfdb-cddb94e52b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'iphone')]</value>
      <webElementGuid>532406d5-d834-4ae3-8224-246f5ea66928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Searches:'])[1]/following::a[1]</value>
      <webElementGuid>5acad627-2dfd-41d4-a3d5-b97f1b976f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='please type in at least 3 letters...'])[1]/following::a[1]</value>
      <webElementGuid>124700e4-1bed-4a0a-8a47-28e164871343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='laptop'])[1]/preceding::a[1]</value>
      <webElementGuid>4313fec9-890f-4449-9aad-c3c9b596693f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ps5'])[1]/preceding::a[2]</value>
      <webElementGuid>5412a43d-cc84-4472-9b02-87ac6388b989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='iphone']/parent::*</value>
      <webElementGuid>c017195f-ea22-4d63-8285-3dd9b04d0b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:klevu_search.getResultsForClickedTerm( 'iphone', 'ps' );&quot;)]</value>
      <webElementGuid>e6b90e31-dd67-4e7a-ba40-4b30781225c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/a</value>
      <webElementGuid>b8a59a3c-0888-43ac-9de9-2bef03c8038c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:klevu_search.getResultsForClickedTerm( &quot; , &quot;'&quot; , &quot;iphone&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;ps&quot; , &quot;'&quot; , &quot; );&quot;) and (text() = 'iphone' or . = 'iphone')]</value>
      <webElementGuid>c0a5b4d9-893c-4d68-b3bc-f63d5319a3d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
