<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_iphones</name>
   <tag></tag>
   <elementGuidId>853a0c19-b221-40d2-9670-25afd90ec867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;iphones&quot;] > span.klevu-filter-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='4popupcategory']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ad2546db-06a9-4337-b30e-ceb05dd734a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>klevu-filter-label</value>
      <webElementGuid>541a77da-1962-4c5c-a348-115f07c62e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iphones</value>
      <webElementGuid>8bbeef36-c19b-443e-a8a8-18a0ed14cb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4popupcategory&quot;)/a[1]/span[@class=&quot;klevu-filter-label&quot;]</value>
      <webElementGuid>81bf5043-790e-4e4e-be84-6091b7da847c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='4popupcategory']/a/span</value>
      <webElementGuid>97fcb5dd-e200-47d5-914d-e27f4b78db52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iphone'])[2]/following::span[2]</value>
      <webElementGuid>0aa7d97a-f580-4ab6-a617-1802581634dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='apple'])[1]/following::span[4]</value>
      <webElementGuid>4a123672-3537-4380-8074-649c9d54537f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='apple iphone promo'])[1]/preceding::span[2]</value>
      <webElementGuid>25e5f869-4868-4749-bb60-938124906579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='products'])[1]/preceding::span[4]</value>
      <webElementGuid>a23c1d1e-9504-49fd-bf07-b12c7dc829ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='iphones']/parent::*</value>
      <webElementGuid>bdd96289-b9c8-4d29-90e4-2c93a416c403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[5]/a/span</value>
      <webElementGuid>f8975411-4cf1-4c9e-ac42-e00c0cef1660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'iphones' or . = 'iphones')]</value>
      <webElementGuid>a240c306-f2d3-4fe4-bd4d-a1aedeb657ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
