<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_products</name>
   <tag></tag>
   <elementGuidId>d22763ed-2de3-4e58-8bbd-f8638f89dd8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;products&quot;] > span.klevu-filter-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='6popupcategory']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21148dd6-4cbb-45e0-a40c-618d2c0b53f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>klevu-filter-label</value>
      <webElementGuid>b6208701-5721-4c8f-8b5e-06f98a8fa14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>products</value>
      <webElementGuid>93f6fcde-3612-4724-ad55-1ee0897cc9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6popupcategory&quot;)/a[1]/span[@class=&quot;klevu-filter-label&quot;]</value>
      <webElementGuid>190f28c2-23fd-4c37-ae45-1a7495459c1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='6popupcategory']/a/span</value>
      <webElementGuid>e0b6023b-a836-4b54-9f40-53084b42e34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='apple iphone promo'])[1]/following::span[2]</value>
      <webElementGuid>5761ddaf-7004-4a54-8d57-2b401fa91bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iphones'])[1]/following::span[4]</value>
      <webElementGuid>822630a0-062e-472f-8d52-f1f55c7a5c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cellphones'])[1]/preceding::span[2]</value>
      <webElementGuid>224e861c-d625-429c-8221-035bf482189b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='screen protectors'])[1]/preceding::span[4]</value>
      <webElementGuid>53ac0088-9463-4473-bf9e-1b7d185b142c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='products']/parent::*</value>
      <webElementGuid>58fea380-5e75-4a2b-b175-63efa7742a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[7]/a/span</value>
      <webElementGuid>efe0e119-993f-4055-afa5-26b37b06ee54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'products' or . = 'products')]</value>
      <webElementGuid>1ca89f27-2245-4cf0-8bd0-9a7409f01ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
