<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order Number_order_id</name>
   <tag></tag>
   <elementGuidId>9e896548-8d9f-40bc-8fd5-2abe1f0bdc93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dae04abc-e539-4612-bd34-7268b07fc0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_id</value>
      <webElementGuid>31c70dab-e491-494d-8cd8-2fdd0225f9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_id</value>
      <webElementGuid>40ffe3c2-dbe9-4311-8d39-5eddfb0a00c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Order Number</value>
      <webElementGuid>d8cbb7ae-737d-4901-9e63-33c95e896075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>6c096c13-00d2-4343-af1f-ab70b20a28e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>534b5370-1473-4734-bcf1-4c136094fe60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true}</value>
      <webElementGuid>5db0b916-f0a2-4328-89ae-ba5b997a900a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_id&quot;)</value>
      <webElementGuid>594c8a80-53a3-4826-b1c7-8e7dbfc8964b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_id']</value>
      <webElementGuid>244a2f67-3055-45eb-8fea-66092b688fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='track-order-form']/fieldset/div[2]/div/input</value>
      <webElementGuid>1e52d79b-548c-4731-bef1-dae19506e3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a31c5f8f-1ac1-4377-af2f-871d24b58496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'order_id' and @id = 'order_id' and @title = 'Order Number' and @type = 'number']</value>
      <webElementGuid>e9abe61f-776f-4895-8f4a-63e7409394bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
