<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Deliver</name>
   <tag></tag>
   <elementGuidId>820c100c-6fcb-4d62-a904-af12e8843610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.shipping-method-select.action.primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b44fec4-25d3-4b3c-8e39-8b512195b2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shipping-method-select action primary</value>
      <webElementGuid>29beb3e1-86a9-4009-8863-ecf4e4d67132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>681de6ff-aa44-4c73-8688-d847fd30fa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>i18n: 'Deliver'</value>
      <webElementGuid>ae36708b-e42c-468a-ab85-5719ba9d1c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deliver</value>
      <webElementGuid>24914f81-4900-415b-a6f4-9a2a2c5a3f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-shipping-method-load&quot;)/table[@class=&quot;table-checkout-shipping-method _multiple&quot;]/tbody[1]/tr[@class=&quot;row method-block active&quot;]/td[@class=&quot;col col-description&quot;]/button[@class=&quot;shipping-method-select action primary&quot;]</value>
      <webElementGuid>ff55ff9b-b33f-4cae-81e4-af7d9d58a18b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>b3f08c99-b129-4e61-b757-7c5790a80963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/table/tbody/tr/td[4]/button</value>
      <webElementGuid>b365ec77-92fc-49c0-9627-ef195446cbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Delivery 2 - 5 Working Days'])[3]/following::button[1]</value>
      <webElementGuid>1bdc49be-07e4-4fd7-9ab4-2c0bcc17857d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Delivery 2 - 5 Working Days'])[2]/following::button[1]</value>
      <webElementGuid>37a8d8bb-505d-4a3a-a2ed-020535e06726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your delivery address &amp; contact details:'])[1]/preceding::button[1]</value>
      <webElementGuid>ae62b7fb-b94e-4916-900c-3cdd0adc7a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/preceding::button[1]</value>
      <webElementGuid>d2e3a2e9-9843-473b-a0ad-5bde79a73079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deliver']/parent::*</value>
      <webElementGuid>f7684547-c480-4c96-850a-e44e40e63f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>728b599c-7a96-4169-ae24-cee9af525e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Deliver' or . = 'Deliver')]</value>
      <webElementGuid>be581d4b-3662-4661-a445-f20047da7c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
