<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Help</name>
   <tag></tag>
   <elementGuidId>f2c168a2-6850-446c-8d26-25f2f094edef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.header-trigger.header-trigger__help > div > div > div > #J6BB4C9 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//p[@id='J6BB4C9']/a)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85dd199a-7b44-4d99-a823-f39297db001f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/services/help-centre/questions-answers</value>
      <webElementGuid>abaada19-2921-4bab-847b-dab7630a8082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Help</value>
      <webElementGuid>4a3bcf9a-61d7-4b3f-952c-39648069d0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html-body&quot;)/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;page-header-inner&quot;]/div[@class=&quot;header content&quot;]/div[@class=&quot;header content__right&quot;]/div[@class=&quot;header-trigger header-trigger__help&quot;]/div[1]/div[1]/div[1]/p[@id=&quot;J6BB4C9&quot;]/a[1]</value>
      <webElementGuid>cccc19cb-4308-40ba-b218-de00812175ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//p[@id='J6BB4C9']/a)[2]</value>
      <webElementGuid>0bce0599-213b-47b9-8eeb-335c42574251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Help')]</value>
      <webElementGuid>6879d755-775e-4e6c-82a1-87ac65a61722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[1]/following::a[1]</value>
      <webElementGuid>1dbbebc1-6008-4e0b-aa7e-5a9eca792ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/following::a[2]</value>
      <webElementGuid>f9e0dd36-e96b-48d5-9566-4f6bf303159f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Star Gaming'])[3]/preceding::a[1]</value>
      <webElementGuid>a71e219d-7f85-4a37-ba12-6a36407ab358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tech for Business'])[3]/preceding::a[2]</value>
      <webElementGuid>d963ea9b-858e-4ecc-b7a3-60755b84d13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Help']/parent::*</value>
      <webElementGuid>4cd83c0b-4556-4ea2-8fa6-2c1b76f4bada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/services/help-centre/questions-answers')]</value>
      <webElementGuid>391a6321-6e48-41e5-a51f-460a6bbdfb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/p/a</value>
      <webElementGuid>a3fdee89-4afe-45c6-9af5-b22e31f93060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/services/help-centre/questions-answers' and (text() = 'Help' or . = 'Help')]</value>
      <webElementGuid>e4140b20-0f05-4408-b41d-075ed9a1484d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
